### ISSUE TITLE
How do I download specific version of Nextcloud?

### ISSUE THREAD

**Issue by dbolton** [nextcloud/vm#1009]
I'm trying to set up an Ubuntu 18.04 LTS server with version 15.0.14 of Nextcloud. (I'm trying to migrate from Ubuntu 16.04 LTS which doesn't have the right version of PHP to upgrade further).

The Nextcloud docs point to this script for manual install but this script seems to always download the very latest version of Nextcloud (currently v. 17). I tried changing line 631 of lib.sh to NCVERSION="15.0.14" but it still downloads v. 17. 

Any advice?

**Comment by enoch85** [comment]
The best option in my opinion is to [upgrade PHP](https://shop.hanssonit.se/product/upgrade-php-version-including-dependencies/) on the current VM.

This is because Ubuntu 20.04 is around the corner, and better upgrade to that directly instead.

You could also choose the [install option](https://shop.hanssonit.se/product/installation-of-nextcloud/).
