### ISSUE TITLE
Updates to the php-package

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1010]
When using the current Nextcloud VM, which is based on Ubuntu 18.03 LTS, what would you say, how long I will get Nextcloud Updates?

Because Nextcloud always needs a current PHP version. And will that be able to run in the Nextcloud VM until 2023 when the official support for Ubuntu 18.03 LTS will end?

In other words: what do you think, does the update script provide updates to the php package until 2023?

**Comment by enoch85** [comment]
When I started out with Linux I wanted cutting edge all the time. Later on I noticed that cutting edge isn't the best, especially if you're not familiar with Linux since it requires extra PPAs and repos that might break.

So, since the Nextcloud VM should be stable as a rock, I decided to only use what the release offers in the main repos. That means PHP 7.2 is the maximum version.

There is a support option for upgrading though: https://shop.hanssonit.se/product/upgrade-php-version-including-dependencies/

**Comment by szaimen** [comment]
> When I started out with Linux I wanted cutting edge all the time. Later on I noticed that cutting edge isn't the best, especially if you're not familiar with Linux since it requires extra PPAs and repos that might break.
> 
> So, since the Nextcloud VM should be stable as a rock, I decided to only use what the release offers in the main repos. That means PHP 7.2 is the maximum version.

Okay, I can understand that decision.
So then I have to upgrade the PHP version manually.
Thanks for the clarification!
