### ISSUE TITLE
Please make the nextcloud_occ command available for the webmin command shell

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1011]
It would be really nice, if you could make the make the nextcloud_occ command available for the webmin command shell. It is one of the few less reasons I have to access the VM for.

**Comment by enoch85** [comment]
Imo you shouldn't use Webmin to administer the VM. Yes, I know it's default, but I've seen cases where Webmin makes a total mess (probably because it's easier to mess up with Webmin for an unexperianced user).

It's better to learn command line, and there's a lot of resources online already.

I say no, but if you make a PR I might think about it.

**Comment by szaimen** [comment]
> Imo you shouldn't use Webmin to administer the VM. Yes, I know it's default, but I've seen cases where Webmin makes a total mess (probably because it's easier to mess up with Webmin for an unexperianced user).
> 
> It's better to learn command line, and there's a lot of resources online already.
> 
> I say no, but if you make a PR I might think about it.

Actually I cannot find any documentation on how to create a custom command for the webmin command shell. So closing.
