### ISSUE TITLE
Disabling the web-updater by default?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1029]
What about disabling the web-updater by default?
Since the web-updater didn't work the last time I've tried it with Nextcloud VM, what about disabling it by default?
From the Nextcloud manual:
![image](https://user-images.githubusercontent.com/42591237/72211333-d7b11900-34c9-11ea-8fcf-2fd8a5d479b6.png)

**Comment by enoch85** [comment]
Hmm, never thought of that. Wouldn't that make the update notification disabled as well?

I would like to have the VMs own notify system. It's possible, but some code is missing in the server still. Maybe next project for you? https://github.com/nextcloud/vm/pull/886/files

**Comment by szaimen** [comment]
I've tested the config option and it doesn't disable the web updater.
But I found this: https://github.com/nextcloud/server/issues/18585

> Hmm, never thought of that. Wouldn't that make the update notification disabled as well

Probably not.

> I would like to have the VMs own notify system. It's possible, but some code is missing in the server still. Maybe next project for you? https://github.com/nextcloud/vm/pull/886/files

Maybe after smbshare is merged.

**Comment by szaimen** [comment]
This is probably how the Netflix snap handles this:
https://github.com/nextcloud/nextcloud-snap/commit/31a623cc5d77f9ddbc1473076c027d13c0f6baeb

**Comment by enoch85** [comment]
@oparoz @kyrofa Hmm, how would you handle that in bash? Just create `ncpath/htdocs/` and then put the same files as you did in there?

**Comment by kyrofa** [comment]
Can you just `occ app:disable`? We do that [with theming](https://github.com/nextcloud/nextcloud-snap/blob/master/src/nextcloud/fixes/fresh-install/1_disable-theming.sh#L9), for example.

**Comment by szaimen** [comment]
Unfortunately not, since it's not a normal app:
If I do `occ app:list`, there is no updater app listed but it is definitely installed and working in the Nextcloud VM.

**Comment by kyrofa** [comment]
Ah. Effectively all the `organize` does is `rm -rf` the app. Might as well just do that.

**Comment by szaimen** [comment]
Ah okay, I get it know 👍
So this would probably not work for the Nextcloud VM since you would loose the update-notifications. We just wanted to disable the web-updater.
But thank you for your fast and helpful reply, @kyrofa!

**Comment by szaimen** [comment]
@enoch85 here another idea:
What about blocking the url http://cloud.domain.tld/updater ?
that is the path to the web updater and if blocked, the web-updater it shouldn't work...

**Comment by enoch85** [comment]
We don't want to hack the code (are not allowed to really) by adding our own stuff in it such as blocking real Nextcloud URLs. It would be very hackish and @jospoortvliet already pointed that out in the past. The Nextcloud VM should deliver Nextcloud "as is" at least from my understanding.

> A second option would be creating a cronjob that checks if a new version is found and automatically posts a notification with the information to the admin group. Then you could disable the updatenotification app.

I think that would be a much better option since then `notify_users_gui()` are in place, and we wouldn't touch the Nextcloud code. Also the VM uses its own CLI updater anyway.

*A third option* would be to be able to execute the CLI updater directly from GUI, really cool, but really insecure as the CLI updater requires root - and yeah, we don't want to go there. :)

If you have time @szaimen it would be great if you could put a PR togehter for discussion.

Thanks!

**Comment by szaimen** [comment]
@enoch85 I honestly don't think that we can substitute all features of the update notification app, but we'll see. (E.g. we cannot delete notifications to my knowledge)

As a note to myself:
I think these are the two important files:
https://github.com/nextcloud/server/tree/master/apps/updatenotification/lib/Notification

**Comment by enoch85** [comment]
> I honestly don't think that we can substitute all features of the update notification app, but we'll see. (E.g. we cannot delete notifications to my knowledge)

What Nextcloud does:
Gives you a notification in GUI about that there's an new update

What the Nextcloud VM would do:
Gives you a notification in GUI about that there's an new update

Did I miss something? 

I'm thinking:
1. Disable the standard update notification sent by Nextcloud
2. Use `notify_users_gui()` and send the same notification, but from a function in the VM that checks if there's a new update or not. 

With that (---^) we could customize the notification text, such as give information about what the user should do (e.g. "Please run sudo bash /var/scripts/update.sh from your CLI") instead of confusing the user by using the Nextcloud GUI updater which doesn't work due to strong permissions in the VM (if you don't change them ofc).

**Comment by enoch85** [comment]
Btw, we should rename the notify function to `notify_admin_gui`.

**Comment by enoch85** [comment]
Very quick and dirty, but something like this as a cronjob:

```
if version_gt "$NCVERSION" "$CURRENTVERSION"
then 
notify_admin_gui \
"Update availabile!" \
 "Please run sudo bash /var/scripts/update.sh from your CLI"
fi
```
