### ISSUE TITLE
Tried to Upgrade from 17.0.2 to 18 and it didn't work.

### ISSUE THREAD

**Issue by cbacit** [nextcloud/vm#1049]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by cbacit** [comment]
@enoch85  Please help me out with this..

**Comment by cbacit** [comment]
https://imgur.com/l8jsobp
https://imgur.com/1SknNiq

**Comment by Powerbless** [comment]
My vm updated Automatic and all fine. Just for You to know.

**Comment by enoch85** [comment]
I've seen this one time before. It seems something is bugging out when trying to run the optimize command, which really is a server issue. 

@MorrisJobke Please shed some light on this. Should this issue be moved?

**Comment by enoch85** [comment]
@cbacit I noticed that it fails with Zimbra, what if you disable that app? Does it work?

**Comment by cbacit** [comment]
It seemed to disable the plug-in's during the upgrade..  

Right now when I view it it says...

How can I disable the plugin or make sure the plugin is disabled...

B/c when I view the site I get these errors.
![Tuesday, January 21, 2020_15h31m50s_003_](https://user-images.githubusercontent.com/47609657/72845066-732d5100-3c63-11ea-8f0b-8246ddfcd268.png)
![Tuesday, January 21, 2020_15h31m33s_002_](https://user-images.githubusercontent.com/47609657/72845068-732d5100-3c63-11ea-962a-f777a8065c8a.png)

**Comment by cbacit** [comment]
> @cbacit I noticed that it fails with Zimbra, what if you disable that app? Does it work?

How can I dis-able the app because right now my nextcloud isn't running b/c this upgrade failed?

**Comment by enoch85** [comment]
@cbacit To be honest it seems to me like you need paid support, or some good Googleing skills. 

You best option right now is to: 
1. Restore from a backup
2. Disable Zimbra
3. Do the update as usual with the script.

The error is thrown due to an error in the app it seems, and that's nothing the script has any control over. The script uses functions from Nextcloud itself (`occ` in this case) and the `occ` command failed because `occ` failed to update due to an error which is out of scope for this VM.

Thanks for posting your issue, but there's not much I can do to improve the code in this case.
