### ISSUE TITLE
[Improvement] Possibility to install onlyoffice document server with self signed cert

### ISSUE THREAD

**Issue by ghost** [nextcloud/vm#1250]
Currently onlyoffice.sh fails when vm is installed with self signed cert:

```
# Check if Nextcloud is installed with TLS
if ! occ_command_no_check config:system:get overwrite.cli.url | grep -q "https"
then
msg_box "Sorry, but Nextcloud needs to be run on HTTPS which doesn't seem to be the case here.
You easily activate TLS (HTTPS) by running the Let's Encrypt script found in $SCRIPTS.
More info here: https://bit.ly/37wRCin
To run this script again, just exectue 'sudo bash $SCRIPTS/apps.sh' and choose OnlyOffice."
    exit
fi
```

But there is possiblity to make documentserver_community works with this type of certs
From https://github.com/nextcloud/documentserver_community

```
Self signed certificates

If your nextcloud is using a self signed certificate for https, you'll need to import the certificate into nextcloud's certificate store to make the documentserver work.

occ security:certificates:import /path/to/certificate.crt
```

Please update onlyoffice.sh to check if nc is installed with self signed cert then make align in config "occ security:certificates:import /path/to/certificate.crt"  and run install

Thanks

**Comment by enoch85** [comment]
Consider:

1. Most of the users downloading the VM don't know what `sudo` is.
2. If we let the user enter that path themselves, how can we verify that the cert actually works?
2. Self signed certs are less secure. Is that really something we should advocate?

Sure, we could do it, but I don't think it's a good idea since it's made very easy to create your own *valid* certificate. If the user would fail to do that the first time, it can easily be run again with `sudo bash /var/scripts/menu.sh`. 

I'm not a fan of making it possible to run a less secure deployment in general.

**Comment by Haxy89** [comment]
1. How this is related? 
2. We don't want to let user enter path to cert themselves, "/path/to/certificate.crt" is the path to nc self signed cert created during installation when user select to not use lets encrypt ssl, we can use this path
3. Agree that self signed certs are less secure but this would be helpfully when user want to use NC only in local network. A lot of people don't want to install NC with external access (I consider it as not secure because I have to open port 80 and 443 on my router to my network). 
I am using NC only in my local network and using vpn to access from outside. 

Would be cool to have possibility to use onlyoffice when our NC is not available directly from outside, 

I think this is why someone prepare possibility to use self signed cert in document server and would be great to use it in vm scripts.

Currently I have to use separate docker container for document server.

**Comment by enoch85** [comment]
1. Meaning: users might type the wrong path, but since you are talking about adding the self-signed (by Ubuntu) then it's not relevant anymore. All users would get the same cert though (my stomach just turned two rounds)
3. That seems like an edge case to me, really. I don't know anyone yet (during my 5 years as dev of this) that they used it only locally.

Users that wants to run this locally will have to do this themselves. "It's just one command" - right? :)

Not 100% decided yet though. Maybe a PR from you would make me rethink my decision.

**Comment by enoch85** [comment]
I've decided not to do this. You have the option to install it totally integrated in Nextcloud, or you can use the docker which is not even the default way anymore.

Installing with self-signed certs sure, but then you're on your own,

**Comment by mhbacks** [comment]
Hi enoch85,
when not adding an option for self-signed certs, what is with a hint in the error message, that you can import a self sign with this `occ security:certificates:import /path/to/certificate.crt` command? 
best regards,
Max

**Comment by enoch85** [comment]
> occ security:certificates:import /path/to/certificate.crt

In the VM we have included `nextcloud_occ` which is the full path to the `occ` command of Nextcloud. So start with running that and see what happens.

You command should be `nextcloud_occ security:certificates:import /path/to/certificate.crt` based on what you just wrote.
