### ISSUE TITLE
Inconsistencies in update notification

### ISSUE THREAD

**Issue by k-matti** [nextcloud/vm#1278]
Running updatenotification.sh gets me info about new version of Nextcloud 
`Checking for new Nextcloud version...
The notification regarding the new Nextcloud update has been already reported! (19.0.0)`

But in Administration -> Overview I can see:

![image](https://user-images.githubusercontent.com/66017397/83741383-6cbed500-a658-11ea-837b-8bfea60b37a7.png)

How can I update to 18.0.5?
Should I use update.sh script? But It wants to update to version 19
Why I didn't get notification about 18.0.5?

**Comment by szaimen** [comment]
You can update to 18.0.5 by running 
`sudo bash /var/scripts/update.sh minor`

**Comment by szaimen** [comment]
@enoch85 I mean we could also check if a new minor update is available but that would complicate things by a lot!

**Comment by k-matti** [comment]
> @enoch85 I mean we could also check if a new minor update is available but that would complicate things by a lot!

Script to check if update exists should works that way.

In current implementation I need to check administration page every time because I don't get any update info about minor chages. I don't want to update to 19.0.0 for now

**Comment by szaimen** [comment]
@enoch85 what do you think?

**Comment by enoch85** [comment]
@k-matti The VM updates faster than the GUI. This is because Nextcloud doesn't push new releases all at once.

The default behaviour is to go to the latest major relase, but as @szaimen said - we made it possible to update to minor versions as well.

The automatic updater in the VM does minor updates, so that would be an option for you maybe @k-matti? Then you don't have to *check administration page every time because I don't get any update info about minor chages* since that would happen automatically.

I don't think we should over complicate things here.

**Comment by k-matti** [comment]
„ The automatic updater in the VM does minor updates, so that would be an option for you maybe @k-matti?”

update.sh script is not a problem here. I know I can run „update.sh minor” problem is with updatenotification script. I have version 18.0.4 and want to be inform that there is version 18.0.5 available not only 19.0.0. Now update notification is misleading for the admins. The script informs that there is new version 19 but nothing about 18.0.5. What If admin dont want to update to 19 imidiately but want to update to minor version. Not update info then

**Comment by k-matti** [comment]
I was thinking about this option in nc settings panel:
![image](https://user-images.githubusercontent.com/66017397/83849794-3cd30880-a710-11ea-802a-30779dcc7f10.png)
Shouldn't it trigger update to 18.0.5 notification the same as updatenotification.sh script?
