### ISSUE TITLE
Reset/Fix "We have detected multiple invalid login attempts from your IP. Therefore your next login is throttled up to 30 seconds"

### ISSUE THREAD

**Issue by GitJamz** [nextcloud/vm#1288]
I use the Nextcloud VM hosted on ESXi. 
I was migrating from anothe rinstance with other login information that I forgot to deactivate.
Now I constantly get this message and handeling nextcloud is super slow on all instances now but works..

Where/how to fix this issue? I have googled for hours and I put 'auth.bruteforce.protection.enabled' => false, in the php file and rebooted. Still same problem..

In the enxtcloud administrators logs I see no new failed logins, only older.. Will this reset itself by time or is there a better way?
I also tried method of:
DELETE FROM oc_bruteforce_attempts WHERE ip = ‘IP address;
But this returned nothing and the documentation on how/where to use this is none existent basically..

**Comment by enoch85** [comment]
Bruteforce mechanism is a built in Nextcloud feature. 

You can allow certain IP addresses in Nextcloud settings. And above that you could enable Fail2ban in the VM (an automated installation with a script) that would harden the settings even further.

It will go away eventually, but you have to log out that client that does the failed attempts.

Since this really is a general Nextcloud question I think you would get better help at https://help.nexcloud.com.

**Comment by laurentperrinet** [comment]
the URL https://help.nexcloud.com/ does not exist anymore.

**Comment by enoch85** [comment]
Please try: https://help.nextcloud.com/
