### ISSUE TITLE
Zero byte file truncate issue with Nextcloud deployed with FastCGI

### ISSUE THREAD

**Issue by MaximilianOnGitHub** [nextcloud/vm#1300]
Hi there,

## Steps to reproduce
Upload a File trought MacOS (https://bz.apache.org/bugzilla/show_bug.cgi?id=57087) or MountainDuck (https://trac.cyberduck.io/wiki/help/en/howto/mount/issues/fastcgi)
will write the File to the ZFS Filesystem with 0kb.

## Expected behaviour
File should be written with the expected file-length

## Actual behaviour
File is written with 0kb.
This happens when you are using MacOS Finder or/and MountainDuck with Windows. (Or probably another WebDav Client).
As Nextcloud has decided to pause the development of an Online-Client, I tested MountainDuck
for Windows in Online-Mode. The Windows WebDav Client is no alternative at this point.

## Server configuration

**Nextcloud server version: 19

**Server OS: Ubuntu 20.04. LTS

**How did you install the VM?:Scripted install from master 

## Network
**Do you use DHCP?: No

**Is port 80 and/or 443 open?:Yes

As per MountainDuck-Issue:

"We are not aware of mitigations for Apache HTTP Server such as disabling any buffering strategies in ​mod_fcgid or ​mod_proxy_fcgi / php-fpm. 
Thus you should avoid using FastCGIand instead use use mod_php which is known to handle chunked transfers correctly."

I would avoid changing the VM/Apache manually as I don't know if the Update-Script would change back the configuration in the future.

Is there a recommended way from your side? / Do you know this Issue?

Thanks for your answer and kind regards
Max

**Comment by enoch85** [comment]
> Update-Script would change back the configuration in the future.

That will not happen. We decided to run PHP-FPM, and it will stay that way.

Since this issue seems like a request to change to `mod_php` - please have a look at [this](https://shop.hanssonit.se/product/premium-support-per-30-minutes/)

I can also mention that we actually don't ["cut off"](https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L343-L344) the stream like you may normally do when using PHP-FPM, since it was causing issues in previous versions. It's also set to be dynamic, which should spawn more PIDs if needed.

**Comment by enoch85** [comment]
After investigating this for like 2 hours it seems like it's not even resolvable by changing to `mod_php`. It's a serious bug in Nextcloud (according to me) and most likley in the Desktop client.

Or, do you think it's no matter which WebDAV client you use?

You can read more here: https://github.com/nextcloud/server/issues/3056 Please post your findings there instead, since it will help the developers to solve the issue.

Thanks!

**Comment by enoch85** [comment]
Here are the post about `mod_php`: https://github.com/nextcloud/server/issues/3056#issuecomment-593747129

**Comment by enoch85** [comment]
Here's the desktop client issue: https://github.com/nextcloud/desktop/issues/1323

**Comment by enoch85** [comment]
Hi again,

I have now investigated this further and checked all the clouds I have access to. It turns out that only my own private cloud had 0 byte files that shouldn't be 0 byte - which is a server that is moved like 3 times dating back to 2014. All the new servers had no issues and they are all using PHP-FPM.

I don't know how to reproduce it, I've tried, but it all turns out stable.

So in other words, I don't know which setting I should change in the VM to improve the handling. `Output_buffer` is already set to on (4096) in `php.ini` ((as had given better results a user posted, instead of setting it to Off) and I don't seem to find any better setting than the existing one for the VM setup.

**Comment by stephenitpro** [comment]
I had to enable the fastcgi_request_buffering in my nextcloud nginx config.  Once I enabled that based on the https://trac.cyberduck.io/wiki/help/en/howto/mount/issues/fastcgi recommendation.  This also affected our webdav client Raidrive which was creating 0K files after upload.

**Comment by stephenitpro** [comment]
The original configuration sample from Nextcloud's documentation for Nginx has fastcqi_request_buffering turned off.  I'm still learning the ramifications of these various switch settings.  I'm running the latest version of Nginx.

**Comment by enoch85** [comment]
@stephenitpro Thanks for the input!

The VM runs Apache though.
