### ISSUE TITLE
nextcloud_update.sh hangs on first run in Hyper-V VM

### ISSUE THREAD

**Issue by johncadengo** [nextcloud/vm#1320]
I downloaded the VM for Hyper-V and after some troubleshooting (only works under gen 1, had to use an iso to run boot-repair from a virtual DVD drive, and set up the ethernet as a network legacy adapter), I finally got it to start running through the first time scripts. When it gets to the `nextcloud_update.sh` script, it hangs. 

## Steps to reproduce
1. Run Hyper-V VM for the first time
2. Answer prompts for first time script
3. Hangs

## Expected behaviour
Should give me progress or allow me to retry or do another step

## Actual behaviour
Hangs. It's been hanging on the same spot for hours but I don't want to restart it because I would have to start from scratch

## Server configuration

**Nextcloud server version:** (see your admin page) Whatever comes with the latest 500gb Hyper-V VM. I just downloaded it yesterday.

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version) Hyper-V VM, the one from the site with 500gb of space

## Network
**Do you use DHCP?** Static IP

**Is port 80 and/or 443 open?** No

## Logs / Screenshots
<img width="1177" alt="Screen Shot 2020-07-14 at 6 37 02 PM" src="https://user-images.githubusercontent.com/561587/87493434-ad1f5480-c601-11ea-9811-3e03129e1a5e.png">

I'm just waiting here on this step. No updates for 2+ hours.

**Comment by enoch85** [comment]
Please remount the VM again and try another time. Probably just a temporary thing. 

What's happening is that it runs `apt update && apt dist-upgrade` so in other words it's an Ubuntu thing, or something in your setup.

Gen 2 VMs will come in the next release.

**Comment by johncadengo** [comment]
I made this purchase to save time. If the answer is to turn it off and turn it back on again... I'm at a loss for why I made this purchase.

When Gen 2 VMs come out, will I have to buy it again or are the upgrades made available to people who bought the Gen 1 VM?

**Comment by enoch85** [comment]
Sorry that it didn't work out for you as expected. The VM has been the same (Gen 1) the past 4 years (since Nextcloud was founded) and this is the first time anyone post an issue like this.

As I already mentioned, you are free to re-deploy the current VM and try again. I'm 99.9% sure there was a temporary glitch in your Hypervisor, disks, or network. It always takes time to install new kernels as they are pretty large in comparison. What I'm 100% sure of is that it's nothing that could have been fixed by changing anything in the scripts or the VM itslef as it's a Ubuntu thing that's run - hence, nothing I have any control over.

There will be no "free download" for anyone using the old VMs, that would mean like several thousands if VMs in that case, and it will not happen. Sorry.

I'm glad that you chose the Nextcloud VM, and as I said, just try again and I'm sure it will work. If not, please report it to Ubuntu so that they can have a look at the kernel installation process.

I hope that was a satisfying answer. :)

**Comment by enoch85** [comment]
Sorry that it didn't work out for you as expected. The VM has been Gen 1 the past 4 years (since Nextcloud was founded) and this is the first time anyone post an issue like this.

As I already mentioned, you are free to re-deploy the current VM and try again. I'm 99.9% sure there was a temporary glitch in your Hypervisor, disks, or network. It always takes time to install new kernels as they are pretty large in comparison. What I'm 100% sure of is that it's nothing that could have been fixed by changing anything in the scripts or the VM itself as it's a Ubuntu thing that's run - hence, nothing I have any control over.

There will be no "free download" for anyone using the old VMs, that would mean like several thousands of VMs in that case, and it will not happen. Sorry. If the new VM happens to come out within the 10 days you have right to download it, sure, then it's all yours!

I'm glad that you chose the Nextcloud VM, and as I said, just try again and I'm sure it will work. If not, please report it to Ubuntu so that they can have a look at the kernel installation process.

I hope that was a satisfying answer. :)
