### ISSUE TITLE
Something happend with collabora after update automatically NC

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#1331]
![SNAG-0603](https://user-images.githubusercontent.com/428820/88421025-683bb080-cdad-11ea-9044-ba773b1bee46.png)

i try to configure and show this for first time after 6 months:

![SNAG-0604](https://user-images.githubusercontent.com/428820/88421139-a1742080-cdad-11ea-9226-7b1ba2376357.png)

next i setting again and show me this:

![SNAG-0605](https://user-images.githubusercontent.com/428820/88421179-b650b400-cdad-11ea-8f4d-7e30599c87e1.png)

but is not working, because i try edit a docx file and show again same warning

![SNAG-0606](https://user-images.githubusercontent.com/428820/88421256-db452700-cdad-11ea-8ddb-f2463f98cf35.png)

pls tell me if i need setup something in command line for solve this issue

Tnks a lot

**Comment by enoch85** [comment]
Hey, it's a known error casue by the new Collabora Docker that needs more stuff in the Apache vhost to function. It's alread fixed in the latest script.

Just re-run the installation again and it should be fine.

`sudo bash /var/scripts/menu.sh` --> Additional Apps --> Collabora.

Hope it helps! Thanks for posting anyway.
