### ISSUE TITLE
Ask users to change variables

### ISSUE THREAD

**Issue by Ark74** [nextcloud/vm#140]
I think that for the sake of automation/ease and user preference we should ask if the user wants/requires to change variables such as:
* Static IP / Over DHCP
* [System user password](https://github.com/nextcloud/vm/blob/Ark74-ask-kblo/nextcloud-startup-script.sh#L667)
* [NC user password](https://github.com/nextcloud/vm/blob/Ark74-ask-kblo/nextcloud-startup-script.sh#L683)
* Also keyboard layout changes #139 

I've proposed that every question only waits for certain time, if no interaction then the default value will be applied.
Which in most of the cases is a denial of the change.

**Comment by enoch85** [comment]
**Passwords**
Well, the system user password is always "nextcloud" so that one is a security risk if not changed. I have been thinking about creating a new password just like we do with MySQL, but haven't gotten that far yet.

To fix this just copy the password variable and put the new password in index.php as well. Make it like 8 digits long. Youŕe welcome with a PR. :)

Same thing goes for the NC password.

**Static/DHCP**
If the user doesen't have DHCP in the router/firewall the script will fail. so if we are about to set static IP that must be in the very beginning of the scrript, and in that case skip the whole network setup. Kind of a tricky one as the network part is pretty nested in the scripts.

**Comment by Ark74** [comment]
* Passwords
Please explain how will the system user password be always nextcloud.
I'm testing instances that are run by a non-root user, each user has its own password defined by the admin on the installation process.
Maybe docker images, VPS will have a different scheme, but it's not a rule.

Static/DHCP
My position here is, don't pause the installation process if we are not giving some choice.
Maybe a choice that will expire with the preferred value. #139

**Comment by enoch85** [comment]
When I release the VM *nextcloud* is the default password. Running this from start is a different matter, then you set your own password from start, but 99% of everyone that uses this VM does it with the released version.

Again, you must think of every aspect. Just because you use the scripts in some way it doesn't mean that everyone else is doing the same thing. The static IP part is automated already and we do not pause that part. And again, you must have DHCP to use these scripts, that's why I wrote as I did ---^

**Comment by Ark74** [comment]
> Again, you must think of every aspect. Just because you use the scripts in some way it doesn't mean that everyone else is doing the same thing. 

Exactly!
This is the point that i'm addressing, just by asking would take into account the 1% and continue with the predefined behaviour if no input is given, the _best_ behaviour, let's say.

**Password**
Change password? [Y/n] <- 20 seconds to answer.
Then force the password change

**Static IP**
Set static IP? [Y/n] <- 20 seconds to answer
Then set static IP.

> The static IP part is automated already and we do not pause that part

It does at line [449](https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L449)
`read -p "Press any key to set static IP..." -n1 -s`

You mention something about keeping the installation simple, i think this approach goes in that direction taking the right choices if no input is given, so the installation can complete without much user interaction, but allow them to make a choice, even when they are the 1%.

**Comment by enoch85** [comment]
@Ark74 Problem with users is that they are convenient. If you ask them to change they will say "no" because *nextcloud* is easy to remember and default. That's what I think anyway. Not good from a security point.

If you read what I wrote before, it's not that easy as just changing to static IP. We have to rewrite the whole network setup. 

@ezraholm50 You input on this?

**Comment by enoch85** [comment]
A better soulution would be to check if the password is "nextcloud" and if it is, then ask the user to change. But I think that's kind of hard as passwd uses hashed values.

**Comment by Ark74** [comment]
> If you ask them to change they will say "no" because nextcloud is easy to remember and default. That's what I think anyway. Not good from a security point.

Well, you got a point there. If for the security & functionality sake they should remain, could we ask for keyboard layout input in order to change it or skip it?
Also replace,
` read -p "Press any key to set static IP..." -n1 -s`
to
```
echo "We'll now setup the VM static IP"
sleep 2
```
That would speed up the installation.

**Comment by enoch85** [comment]
> Also replace,
read -p "Press any key to set static IP..." -n1 -s
to 
echo "We'll now setup the VM static IP"
sleep 2

Granted.

> could we ask for keyboard layout input in order to change it or skip it?

Change the PR and show me what you mean.

**Comment by Ark74** [comment]
I've updated the changes.
Sorry they are incremental. But the last result, is the sum of them.
