### ISSUE TITLE
Corrupt file after two download attempts. Please fix this!

### ISSUE THREAD

**Issue by atson-eng** [nextcloud/vm#1499]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Distances over the internet are quite long sometimes, and between our server and yours there might be issues along the way. 

There's been user in the past emailing us regarding the same thing, it happens like 6 times per year give or take - so it's not something new to us. But, at the same time there's not much we can do about corrupted files due to issues between you and our server. There's nothing wrong on our server - and usually the issue turns out to be your own ISP, or that something in between was causing it.

My advice is to try again in a few hours from a different network, and if that doesn't work, then try again tomorrow.

If the issue persists, send an email and I can put the download on a server which is located in Signapore (our mirror) if that's closer to where you try to download it from? Our main server is located in Sweden.
