### ISSUE TITLE
Don't touch maintenance mode in the update script

### ISSUE THREAD

**Issue by oparoz** [nextcloud/vm#158]
`occ upgrade` is managing the maintenance mode. There shouldn't be a need to have the extra lines which enable/disable it anymore.

**Comment by enoch85** [comment]
Thanks! Will double check when the next version is released.

**Comment by enoch85** [comment]
@oparoz I haven't tested but I needs to be set manually, otherwise it will stay in maintenance mode afaik and mess up the rest of the script. Also I'd rather put it in maintenance mode before be remove the whole folder so that stuff can't be written to it and cause data failures. That's why I put a `sleep` of 5 seconds before everything starts...

"Don't change anything that is working" someone once said.

Feel free to make a PR and test, or to close.

**Comment by oparoz** [comment]
I guess it makes sense in case someone wants to install an app while we're preparing for the upgrade.
