### ISSUE TITLE
VirtualBox image stuck at boot

### ISSUE THREAD

**Issue by martinrotter** [nextcloud/vm#1635]
It stays on this screen forever. I just imported OVA appliance and launched the machine:
![image](https://user-images.githubusercontent.com/1255302/97469593-dd87c600-1946-11eb-9e1a-5afa5fd21fed.png)

**Comment by enoch85** [comment]
Hi, 

Even if VirtualBox works, it's not recommended by us due to errors like these. Trust me, I've worked with all kinds of hypervisors, but there's always been issues with Virtualbox in most setups I've used.

Try VMware, it's free: https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html

**Comment by martinrotter** [comment]
Will try and report back.

**Comment by enoch85** [comment]
@martinrotter Any news?

**Comment by martinrotter** [comment]
Oh, I forgot. You were somehow correct. It seems that in VMware the image works just fine. Thank you.
