### ISSUE TITLE
grub-probe: error: unknown filesystem.

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1694]
```
grub-probe: error: unknown filesystem.
/usr/sbin/grub-probe: error: unknown filesystem.
Found Ubuntu 20.04.1 LTS (20.04) on /dev/mapper/ubuntu--vg-NcVM--snapshot
done
Maintenance mode already disabled
Trying to automatically update all Nextcloud apps...
Your apps are already up to date!
Checking for new Nextcloud version...
Latest release is: 20.0.2. Current version is: 19.0.5.
```

cc @szaimen 

Saw this during an upgrade at a customer.

**Comment by szaimen** [comment]
@enoch85 This is an issue of update-grub because all partitions get scanned while updating grub for existing bootable partitions (and snapshots). But this message hasn't caused any issue in my testing. Also update-grub returns `0`  if this message appears (so it works without issue except this message)

If you want to suppress this message, we could add `GRUB_DISABLE_OS_PROBER=true` to `/etc/default/grub` which does this:

![image](https://user-images.githubusercontent.com/42591237/100004920-7edc2d80-2dc8-11eb-9b1c-560fd86ae622.png)

**Translation:** _If this variable is added with true, a renewed check for other operating systems on the PC is suppressed during an update grub. This means that only the kernel images contained in the /boot directory and your own scripts are recorded in the Grub menu according to the numbering._

**Comment by szaimen** [comment]
BTW: this only happens if you have opted in to use snapshots (during the nextcloud_install_script) which is still not the default.

**Comment by szaimen** [comment]
if opened #1695 with a fix
