### ISSUE TITLE
Inconsistent browsing behavior HTTP vs. HTTPS

### ISSUE THREAD

**Issue by flobernd** [nextcloud/vm#1758]
## Steps to reproduce

1. Deploy "official" nextcloud vm appliance (not the full one)
2. Finish initial setup

## Expected behaviour

The nextcloud should be available when browsing one of the following urls:
- `http://hostname/`
- `https://hostname/`

HTTP and HTTPS should both directly lead to the Nextcloud login page / dashboard.

## Actual behaviour

Browsing `http://hostname/` leads to the "Installation finished" info page.
Browsing `http://hostname/nextcloud` leads to the Nextcloud login page / dashboard.
Browsing `https://hostname/` leads to the Nextcloud login page / dashboard.

## Server configuration

**How did you install the VM?** Used prebuild .ova image from the netcloud website (not the full version)

## Network
**Do you use DHCP?** No

**Is port 80 and/or 443 open?** Yes

**Comment by enoch85** [comment]
That's by design.

**Comment by flobernd** [comment]
Can you elaborate the reasons behind maybe? 

I found this pretty counter intuitive. "Fixed" it by removing the 0000-default.conf which hopefully was the correct way here.

Took me some hours to debug it as I first assumed there has to be something wrong with my (rather complex) network/proxy configuration.

**Comment by enoch85** [comment]
Sure, no problem!

**The full version of the Official VM**

In cases were users don't run the TLS setup script (which disables 000-defualt.conf and forwards all traffic to 443), they should be informed that it's possible to do so.

To provide that information, among other useful information, we chose to add that index.php file on port 80. That gives us the opportunity  to easily update information that is relevant to the end user as most users probably don't read all the information boxes when running the script setup (yes, out of experience that's actually the case).

The index.php file is not indexed by search robots, an is only visible until you run the TLS script, or disable the 000-default conf as you did. 

**The Official stripped down vanilla VM**
That's another story, since we don't provide any scripts to help the user setup any security. You get vanilla Nextcloud, nothing else. That's also by design. 

The "official VM" is not meant for production. It's for testing purposes only, and personally I'd like users to only download the full version to get the full experience and not nothing that isn't even giving them free TLS. Hey, both are free.

Still, the information is there since we try to not have too big differences between the code of the official and full version. It's harder to maintain two  completely different versions, so what we did was essentially to just remove some major parts of the code from the official one. The index.php page are nested into different scripts and touches several files, so that's harder to just remove and at the same time keep the two branches as similar as possible.

I hope that explains it.

**Comment by flobernd** [comment]
Thanks for the detailed explanation!

I know how difficult it is to maintain different versions of a specific project so I totally understand.

Might it be possible in the future to provide another full version that does not contain a preconfigured disc, but instead uses a subdirectories of /mnt for the data path?

**Comment by enoch85** [comment]
> does not contain a preconfigured disc, but instead uses a subdirectories of /mnt for the data path?

I'm not sure what you mean?

You are free to use the scripts to setup the server yourself. Then you can chose whatever you prefer.

The whole idea in this project is to pre-configure it to some extent so that the setup becomes easier. 

The data is already in /mnt/ncdata btw.

**Comment by flobernd** [comment]
You are right, I looked incorrectly. Thanks!
