### ISSUE TITLE
Internal Server Error - Postgresql failed

### ISSUE THREAD

**Issue by polzy** [nextcloud/vm#1762]
Hello,

I have a problem since this morning, I have nextcloud VM on VMware and Windows 10 for 1 year, I only update it.
And since this morning on the web page, I have the error:

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

When starting the server, I have the error:
![vmware](https://user-images.githubusercontent.com/1337715/104123952-52677b00-534e-11eb-8ddf-d0e534f1f42f.png)

When I type in the console systemctl status postgresql@12-main.service I have the error:
![sql](https://user-images.githubusercontent.com/1337715/104123955-57c4c580-534e-11eb-898c-831cd0e81228.PNG)

And when I do, a sudo bash /var/script/update.sh I have:
![update](https://user-images.githubusercontent.com/1337715/104123961-5b584c80-534e-11eb-9247-a18b2cc111b5.PNG)

Do you know where this problem can come from? I am very annoyed.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version: 
20.0.4 or 20.0.3 

**Server OS** 
Ubuntu on VMWare Workstation 15.5.2 on Windows 10 last build 

**How did you install the VM?** 
Scripted install from master

## Network
**Do you use DHCP?**  
Static IP

**Is port 80 and/or 443 open?**  
Yes

################  Please use https://0bin.net for long error messages or logs. Thanks! ################
-->

#### Log file (/var/log/nextcloud/nextcloud.log)
I do not know how to recover them, the copy and pasted is impossible

Thank you so much,

**Comment by szaimen** [comment]
> Do you know where this problem can come from? 

No, nothing that I am aware of. I am running the VM currently in a setup comparable to you and I have never encountered this issue. So it must have something to do with your setup.

My recommendation is to restore a working Backup of your VM and hope that it doesn't break again. 
Otherwise please use the forum to get help: help.nextcloud.com

@enoch85 fyi

**Comment by enoch85** [comment]
@polzy You didn't provide any steps to reproduce this error. 

You must have been taking some steps to get to this point. I've been running the same VM since 2016 without any issues based on this repo. It's very rare that a server just crashes without any user intervention. It never happened to me. In the end it was always something I did that caused it.

Most likely you:

1. Upgraded from 18.04 to 20.04 without taking the necessary steps
2. You installed an app from the app store that's not compatible with the current Nextcloud version
3. You turned on automatic updates, and they failed on you (hence we always recommend to keep backups)
4. You made something with the DB that caused this
5. You didn't have enough RAM and the DB crashed
6. You are running too many users but didn't take into account to change the DB config and optimize it.

I'm just guessing here, and I could go on with more probable causes. Without a proper description of how this happened, just providing the actual error - it's hard for us to help you.

Like @szaimen said, there's a forum for support. You could also buy hands on [support](https://shop.hanssonit.se/product/premium-support-per-30-minutes/) in the shop if you want me to have a look at it.
