### ISSUE TITLE
Recommend notify_push if no errors get reported

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1855]
I'm thinking we will test this in NC 21, if we get no bug report we can at least choose it as a recommended app (marked YES) during the setup. AFAIK, it only works with TLS setup, so it can't be made default in the installation script.

_Originally posted by @enoch85 in https://github.com/nextcloud/vm/issues/1853#issuecomment-785885237_

**Comment by enoch85** [comment]
I just had two customers with errors, it still feels unstable. Let's close this.

**Comment by szaimen** [comment]
What was the problem there?

**Comment by szaimen** [comment]
@enoch85 what about this one? What was the issue here?

**Comment by enoch85** [comment]
It's a brand new feature. We don't want to recommend something that isn't rock solid and I've seen issues with it. Can't tell you exactly which ones now, but my own issue is that I can't get it to work behind a reverse proxy, and many users use that.

It's not just something that works. The VM is not for testing (your own configs), it's a stable product. Just because it works for you it doesn't m... We've been over this already ;)

**Comment by szaimen** [comment]
I actually didn't want to discuss whether we make this the default but more to here what didn't work in the install script for notify push. Or wasn't it the script that didn't work?

**Comment by szaimen** [comment]
@enoch85 so the issue wasn't an issue with my script but with the notify push backend itself?

**Comment by enoch85** [comment]
I can't remember now, but I know for a fact that it works like 50/50. It always feels like a gamble when you install it.

I'm sure your script is fine.

**Comment by szaimen** [comment]
Thanks! That's everything I wanted to hear :P
