### ISSUE TITLE
No option for moving data datadirectory

### ISSUE THREAD

**Issue by unpairedliabilitylibrarian** [nextcloud/vm#1903]
Hi guys, I did install the "VM" in my Proxmox Ubuntu 20.04 LXC. 
I did mount my 3TB HDD to the LXC to /mnt/storage by following these steps. https://pve.proxmox.com/wiki/Linux_Container#_bind_mount_points
It is a fresh installation and I want to use /mnt/storage as datadirectory, but unfortunately I had no option to set the folder initially.

Thank you!

**Comment by enoch85** [comment]
Hi @unpairedliabilitylibrarian,

If you need support regarding Proxmox, please ask in those channels.

We use `/mnt/ncdata` which in turn is mounted with ZFS. If you want to use something else, you have to do manual changes on your own.

**Comment by sgtpepperaut** [comment]
i think he was asking for an option to set the datapath on install. i have the same requirement. my use case is proxmox as well. It took about 15 minutes to disable all ZFS related things and mount a new store. Since the proxmox host (preferably runs on zfs or qcow2) anyways the internal ZFS will be redundant. COW on COW file system is slow and unnecessary. If i had to make a whish it would simply be a "would you like to use ZFS as your filesystem or mount your own" :) thanks for the great work . If i get a around to it i will write up an install guide in proxmox.

**Comment by szaimen** [comment]
> If i had to make a whish it would simply be a "would you like to use ZFS as your filesystem or mount your own

Thats actually already possible:
https://github.com/nextcloud/vm/blob/3ce087adf4b50d5a26b28431c828f413e37b851f/nextcloud_install_production.sh#L250-L254

**Comment by Cris70** [comment]
> i think he was asking for an option to set the datapath on install. i have the same requirement. my use case is proxmox as well. It took about 15 minutes to disable all ZFS related things and mount a new store. Since the proxmox host (preferably runs on zfs or qcow2) anyways the internal ZFS will be redundant. COW on COW file system is slow and unnecessary. If i had to make a whish it would simply be a "would you like to use ZFS as your filesystem or mount your own" :) thanks for the great work . If i get a around to it i will write up an install guide in proxmox.

Hi @sgtpepperaut I have the same problem and I would like to disable ZFS as well, but I need help and I did not find other information online. Could you please contact me at criguada at gmail dot com?
Sorry for abusing this issue, but I did not find another way to contact sgtpepperaut.
