### ISSUE TITLE
Sometimes ZFS-Pool is not available, restart hangs with message "stop job runnig for ZFS Event Daemon"

### ISSUE THREAD

**Issue by sven-reichelt** [nextcloud/vm#2243]
### Steps To Reproduce

It's hard to reproduce this error exactly, already had this problem with 2 Nextcloud VM (independent) under Hyper-V.
VM was set up according to the documentation and actually has no special configuration worth mentioning.

### Expected Result

The problem is that you can log into the Nextcloud using the website and/or app, but then you can no longer access the data (although the files are displayed). Likewise, no new upload can take place.

### Actual Result

At this time the state of the ncdata pool is UNAVAIL.
If i try to reboot the vm (e.g. via commandline, the Hyper-V Connetion shows me "A stop job is running for ZFS Event Daemon (zed)" with a timer, but nothing happens. Manual power off the VM and power on works well.

### Screenshots, Videos, or Pastebins

![zed](https://user-images.githubusercontent.com/100131316/154945413-99b70390-b29c-4e59-96b5-55ec576bd096.JPG)

### Build Version

23.0.2

### Environment

By downloading the VM

### Environment Details

Hyper-V on WinServer2019

**Comment by enoch85** [comment]
Hi,

Thanks for posting!

Usually it's due to faulty hardware or that it's mounted the wrong way inside the VM when created/imported. I can't reproduce your error, and I've been running the VM from this repo for the past 2 years on my own servers. We also have a lot of users whic done the same. 

Always when this error occurs, the error has been on the user side.

If you need help, we kindly ask you to visit the forum or get support from our shop.
