### ISSUE TITLE
Bug in FTS

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2347]
@Ark74 Can you have a look at this?

Happened when a user reinstalled from the old version of the docker image.

![image](https://user-images.githubusercontent.com/4511254/173034521-af14e019-5e3c-4646-832a-8fe56c7f4daa.png)

**Comment by enoch85** [comment]
Don't know if this helps?

https://stackoverflow.com/questions/72104770/could-not-validate-a-connection-to-elasticsearch-unknown-401-error-from-elastic

**Comment by bleomycin** [comment]
+1 for me, first run through of the installer on a clean "VMware / VirtualBox (.OVA):
Nextcloud VM [Pre-installed – 40 GB]" VM from hansson it. Also received the exact same error when running nextcloud_install_production.sh on a fresh ubuntu 22.04 VM.

**Comment by Ark74** [comment]
Hmmm, I'm a bit confused, to be clear, is this happening with the current opensearch implementation?
Or while reinstalling from a Elasticsearch implementation?

@enoch85 can you share steps I can follow to reproduce the behavior?

**Comment by enoch85** [comment]
@Ark74 Actually, just run the installer and you'll see. It doesn't matter if it's a fresh install, a reinstall or a manually uninstalled which later is "fresh installed".

This is current master, so yes, open search.

**Comment by Ark74** [comment]
@enoch85 This issue presents because of major changes among versions, 1.x to [2.x](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.0.0.md) released a couple of weeks ago.

Version 2.0.0  changes authorization mechanisms and requirements that might not be possible to meet under current Fulltextsearch app design, since we track latest releases we are now pulling v2.0.0 which will require at best, some redesign.

We might want to track 1.x, which is a stable and supported version while we discuss the future for 2.0 and 3.0 (2023).

Regards.

**Comment by Ark74** [comment]
Systems affected by this issue might want to use:

```
docker system prune -a
```

Before running the updated script.
Cheers.

**Comment by enoch85** [comment]
Thanks @Ark74! :1st_place_medal:
