### ISSUE TITLE
Nextcloud VM Install To Virtualbox Does Not Enable "Enable EFI"

### ISSUE THREAD

**Issue by Jim-Joat** [nextcloud/vm#2409]
### Steps To Reproduce

1. Open VirtualBox
2. Select 'File => Import Appliance
3. Select  file "40GB_Nextcloud-VM_www.hanssonit.se.ova"
4. Install .ova 
5. Wait until script stops running.
6. Stop created  Nextcloud-VM
7. Right click on created VM, select "Settings"
8. Click on "System"
9. Select " Enable EFI (special OSes only)"
10. Click "OK"
11. Start VM again to continue script
12. 

- Note:  In my case the script stops later because the Nextcloud data folder is missing .ocdata, see picture! 

![data folder](https://user-images.githubusercontent.com/8794529/198893770-2757d375-cbb2-431f-af4c-4fe8262e782a.png)

### Expected Result

I expected the script to complete. In this case manually checking " Enable EFI" allowed the script to continue on.

### Actual Result

 Script did continue and I then I received another error shown in picture below. I have sent contact report to www.hanssonit.se/#contact. I do not know if the script problems are related!
![data folder](https://user-images.githubusercontent.com/8794529/198894243-14c0839c-a788-4d88-9a20-a2398dac0126.png)

### Build Version

24.0.5  ??

### Environment

By using the scripts, By downloading the VM

### Environment Details

Operating System: Windows 11 21H2
VirtualBox : 6.132

**Comment by enoch85** [comment]
This is not a script related problem. It's either VirtualBox that's not compatible with the setup in the VMDK files, or that some other error happens during import. 

If on Virtualbox: Please setup a new VM and use the VMDK files from the download, instead of trying to import the files directly. The import only seems to work on VMware, where the VM is created originally.
