### ISSUE TITLE
update.sh in hansson VM is breaking nextcloud

### ISSUE THREAD

**Issue by shibby170** [nextcloud/vm#2413]
### Steps To Reproduce

Run update.sh

### Expected Result

After it completes successfully, it reboots the VM and then nextcloud is up and running afterwards.

### Actual Result

After it completes successfully, it reboots the VM and then nextcloud shows server unavailable error.  I have the update script set to run automatically once a week, so everything is up to date otherwise.  Last weekend everything went fine, and now this weekend it is breaking something in nextcloud.  It seems like it is updating from 24.0.7 to 25.0.1.  Maybe something related to that?

### Build Version

24.0.7

### Environment

By downloading the VM

### Environment Details

I have purchased the Hansson IT VM (multiple times over the years).

**Comment by enoch85** [comment]
Hi,

Thanks for reporting!

I've had automated updates for as long as they existed, and they never failed. One example is our mirror: https://mirror.hanssonit.se

It's impossible to answer what went wrong, but the thing with automated updates is that things can break without you knowing. Often problems doesn't show up until you reboot. So yeah, it might be related to the 25.01 upgrade, or it might not. Someone would need to take a look at it to decide what's broken, and not until then it can be fixed. 

Also, in newer versions of the update script (since 1-2 years back) we don't upgrade between major versions. So that tells me yo don't run on the latest code.

If you want help, you're welcome to reach out in our support channels.

**Comment by enoch85** [comment]
Nope, not any new major code. Just that Nextcloud got to NC 25.

It's always better to run manuaal updates to catch these issues. I can't reproduce it and I've been running automated updates since forever. :)
