### ISSUE TITLE
Improve "appliance" feeling

### ISSUE THREAD

**Issue by mamama1** [nextcloud/vm#2490]
Since something like LTS releases with lifecycles of at least one, two or even three years for people who don't care about frequent feature updates and just want their security issues to be fixed on a patch basis propably isn't gonna happen, I'd really dig an improvment to the appliance in a way that it gets more of a "set and forget" product which an appliance is basically for.

I'm once again in a situation where I didn't realize multiple major releases (which I absolutely don't care about) were published and I'm once again in a situation where I can't just "press upgrade" to get up to date. Instead, I get an offering to buy an upgrade service to fix this issue.

To be honest, that's not what an appliance is supposed to be and this also truly feels kind of scammy. I know you guys have to make money but please find different ways to do so. At least provide documentation on how to fix this so I don't have to dig through brown stuff every time.

I know that it is my fault but now that I looked it up, I'm even more mad that major releases and EOLs are happening like every few months. That's insane, I have other stuff to do than to permanently babysit my Nextcloud instance.

Oh and just to prevent comments on "how can you stay on an unsupported version, you're gonna get hacked": No, I'm not gonna get hacked. My Nextcloud server is only reachable via LAN.

I like the software and I like the features and the possibilities but I'm once again truly mad at several methods of operation with Nextcloud.

edit:
I have now finished upgrading from Nextcloud 23 to Nextcloud 26 and it was **not fun** at all. I even had to manually upgrade to PHP 8 on Ubuntu 20.04.6 LTS. If this was a server installed by me, I would not complain. But this thing is being sold as an appliance and when I have an appliance I don't want to deal with stuff like that.
Calling this thing "appliance" is a massive overstatement. It is just a bunch of install and update scripts but by far no real appliance solution where you don't have to care about stuff at all other than pressing an update button from time to time and backing up your config to somewhere safe.

As soon as this thing breaks for good, I'll replace it with a server installed from scratch by me.

**Comment by enoch85** [comment]
Thanks for your suggestion.

The VM is setup and forget, especially if you don't care about updates.

If you actually fo care though, the one thing you need to do is to run the built in update script like 1 time every 6 months (or depending on when Nextcloud makes a major release.

You can automate it by a crontab. We automated this as well, just use the menu script to set up Automatic Updates, and if you want to go major each time - just remove the 'minor' flag.

**Comment by github-tomster** [comment]
@mamama1 well written 👏🏻 
it may help a lot to see this as a WiP/alpha and to have no expectations at all 🤷🏻‍♂️ 
unfortunately there is misleading 'marketing' and 'advertising' saying some complete different 🙄 
and on top 'money making' can not be prevented 💭 
i can [FEEL](https://github.com/nextcloud/vm/issues/2480) your 'FUN'

it is nice to read: `As soon as this thing breaks for good, I'll replace it with a server installed from scratch by me.`
when you have finished reinventing the 'nextcloud-vm' with no problems/bugs let me now 😉 

i can confirm: this VM is `setup and forget` as best as one can get 🚀 from no expectations 😀 
however all stuff inside has tons of issues and will have in the future 🤪 
is T&M able to fix these ❓ all of them ❓ forever ❓ 🤔 

@enoch85 
you are doing great! 👍🏻 
and i hope you carry on! 🐎 

for me i only can contribute by investing my precious time to write
'feedback' and 'experiences' from the field of mine and maybe it helps a 'project' to evolve 🐒

**Comment by enoch85** [comment]
@github-tomster 

> WiP/alpha

That's actually insulting. This has been a project since 2014, even before Nextcloud was founded (ownCloud).

We made it easy to set up and run Nextcloud. We continue to improve and have always been ever since the first commit. In regards of updating, [please read my last post](https://github.com/nextcloud/vm/issues/2490#issuecomment-1541870041), that's how it works and nothing we made up. **You can't upgrade Nextcloud between major versions**.

From the [Nextcloud manual](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html):

> Nextcloud must be upgraded step by step:
> Before you can upgrade to the next major release, Nextcloud upgrades to the latest point release.
> Then run the upgrade again to upgrade to the next major release’s latest point release.
> You cannot skip major releases. Please re-run the upgrade until you have reached the highest available (or applicable) release.
> Example: 18.0.5 -> 18.0.11 -> 19.0.5 -> 20.0.2

Basically, care about updating, or be at risk - it's your choice. As already mentioned, we already automated updates, and sure, we could choose to do major versions as well, but from *experience* we chose not to, since it will probably result in a broken Nextcloud.

You can read how we make it easier [here](https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=W7D3quPiqQz3_MsE).

> tons of issues and will have in the future 

Feel free to open a report regarding these issues, maybe it's user errors, maybe it's actual bugs? Also from *experiance* I can state that we have several thousands of users (probably several 100K, but we don't count) that don't have issues like you are having. That tells me that all is working pretty nice. 

Closing this now since the question is already answered.

**Comment by enoch85** [comment]
One last thing @mamama1 

> where you don't have to care about stuff at all other than pressing an update button from time to time and backing up your config to somewhere safe.

Let's break this down:

1. 
> where you don't have to care about stuff at all other than pressing an update button from time to time and backing up your config to somewhere safe.

It's not pressing a button, but running an update script - which can be automated if you think that running one single command is annoying.

2. 

> backing up your config to somewhere safe.

No need, it's already done (hint `ls -l /mnt/NCBACKUP && ls -l /mnt/NCBACKUP-OLD`), but as you know - best practice is always to make a snapshot before. You never know. 

**On topic:**

Personally I installed a server like 4 years ago which is the only one I automatically update. Guess what, I haven't touched it at all apart from upgrading PHP when Nextcloud required me to do so - something that you also are notified that you need to do through Nextcloud Notifications (also a small improvement from us). 

And yeah, it's a bunch of script that compiles the end product, which is an appliance.

**Comment by enoch85** [comment]
@mamama1 

> please either at least provide documentation on how you want it to be done so your user's appliances conform to your "blueprint"

Already said it:

> the one thing you need to do is to run the built in update script like 1 time every 6 months (or depending on when Nextcloud makes a major release).

Above that, use us to update needed dependencies,  or try it yourself.

And: https://docs.hanssonit.se/

Basically, we tried (try) to make it as easy as possible, without limiting users that want to explore. We keep everything as default as possible. We allow root so that you can do stuff on your own. But if you mess up or lack the knowledge, we are here to help. Personally, I think that's a pretty nice business model - we don't ask anything of you, but you are welcome to use our service *if you need*.

**Comment by mamama1** [comment]
TBH this is nothing I want to rely on. As already stated, I want to exactly know how you expect installations in the field to look like so your stuff (scripts) continues to work. If there ain't no documentation on how you want the PHP upgrade (or OS upgrade, if we look into the future) to be done, which parameters need to be set, and so forth, the whole thing is just russian roulette for me and I'm gonna ditch it as soon as I would need to buy support.

BTW, once in a while bitwarden just disappears and I have to redeploy it with /home/bitwarden/bitwarden.sh start. usually, after your update script ran. Today it told me "Due to compatibility issues with Bitwarden and Watchtower, we have removed Watchtower from this server. Updates will now happen for each container separately.".

This time it even was completely shot:
`ERROR: for web  manifest for bitwarden/web:2023.4.1 not found: manifest unknown: manifest unknown
ERROR: manifest for bitwarden/web:2023.4.1 not found: manifest unknown: manifest unknown
`
Nice! 
Next time I'll install bitwarden on a separate VM by myself too.

**Comment by enoch85** [comment]
Well, maybe it's user error, maybe it's hardware issues, maybe it's configuration issues, maybe it's you upgrading PHP on your own..
 Or maybe not.

All I can say is: it works fine for me and all the servers I (and my former company) runs, without *any * issues that you're stating. In case you missed it:

> Personally I installed a server like 4 years ago which is the only one I automatically update. Guess what, I haven't touched it at all apart from upgrading PHP when Nextcloud required me to do so

That's years without any issues and still going.

**Comment by github-tomster** [comment]
@enoch85 
i am sorry you feel sad. please do not just read what you want to read. and it is not just about "your" nc-vm/scripts ❗ 
it may help to consider what expectations can be disappointed 💡 
however if you like to call it bug-free/error-free/whatever - just do it 🦄 
one can take a look at this:
https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aopen+label%3Abug
or this:
https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aopen+label%3Aregression
[the list is endless by design 😉]
if interested.
well... 🙄
