### ISSUE TITLE
cannot import 'ncdata': no such pool or dataset

### ISSUE THREAD

**Issue by orboan** [nextcloud/vm#2512]
### Steps To Reproduce

1. Import Ova for VirtualBox
2. Execute script as ncadminonce Ubuntu booted
3. Script says it cannot continue as data dir with .ocdata was not mounted
4. Checking logs while booting (after restarting) I find

Please systemctl status zfs-import-cache.service to find out more info about this error.
Runnig systemctl status zfs-import-cache.service I get
cannot import 'ncdata': no such pool or dataset

### Expected Result

After importing ova and running script, nexcloud is working.

### Actual Result

cannot import 'ncdata': no such pool or dataset
Nextcloud does not start.

### Build Version

last ova published to the date

### Environment

By downloading the VM

### Environment Details

VirtualBox 7.0.8 
Host is Windows 10

**Comment by enoch85** [comment]
Thanks for reporting! Please check the documentation: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions?currentPageId=W6yngePiqQz3_Mpc

We generally don't recommend Virtualbox due to (sorry) shitty drivers. Yes it's opensource and that's super nice and all that, but we got hundreds of reports regarding Virtualbox doesn't work, while VMware works much, much better - and it's free! :)

Conclusion, it if works on VMware, but not Virtualbox, then it's nothing wrong with the OVA, rather the hypervisor it's run on.
