### ISSUE TITLE
PHPMyAdmin & Webmin optional software

### ISSUE THREAD

**Issue by Pe46dro** [nextcloud/vm#39]
I think that PHPMyAdmin & Webmin should optional during the installation, i think that software like this shouldn't be in production purpose environment.
A `/phpmyadmin` endpoint decrease the system security

**Comment by enoch85** [comment]
The whole purpose and design of the VM is to make it as easy as possible for Llinux n00bs to get Nextcloud up and running in no time, without having to write any commands at all. That's why Webmin is default, so that the user gets an GUI to work with. Webmin is only run locally until the user opens port 1000 in the router/firewall, so no outside access.

phpMyadmin is there to make it easier to administer databases (obvious) and access is forbidden in the conf, until the user actively changes this.

So all and all, it is secure.

**Comment by enoch85** [comment]
@Pe46dro Any objections?

**Comment by Pe46dro** [comment]
Ok, i don't have objections, but i think that a simple [Yes/No] questio shouldn't be a problem.

**Comment by enoch85** [comment]
As a new user (n00b) you don't know what either Webmin or phpMyadmin are. I think it's better to install it securely than to let the user install it later on with unsecure settings. It makes no harm as access is forbidden.

I will close this, thanks for your suggestion.
