### ISSUE TITLE
Failed authorization procedure

### ISSUE THREAD

**Issue by coldwolf2000** [nextcloud/vm#452]
## Steps to reproduce
1. I have a single nextcloud server. I am trying to get Collabora running. I have 2 subdomians one for the nextcloud server and one for Collabora. both are pointing to the server and port 443 is open
2. I run the Collabora.sh script and I get an error 
3. I am using lets encrypt for the SSL cert

## Expected behaviour
it should complete

## Actual behaviour
the error I get is 
Failed authorization procedure. office.coldwolf.info (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: The key authorization file from the server did not match this challenge [x4gyiYoPNvDTSCNf1wSv9feBwdz1T_hqXNDCKcPbHoE.chi-WDZesVf1rkqKiqEsryE7nk_eMHdjX4tJM293XME] != [ACME client standalone challenge solver]

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: office.coldwolf.info
   Type:   unauthorized
   Detail: The key authorization file from the server did not match
   this challenge
   [x4gyiYoPNvDTSCNf1wSv9feBwdz1T_hqXNDCKcPbHoE.chi-WDZesVf1rkqKiqEsryE7nk_eMHdjX4tJM293XME]
   != [ACME client standalone challenge solver]

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

It seems like no certs were generated, please report this issue here: https://github.com/nextcloud/vm/issues

## Server configuration

12.0.5

**VM version** It is the one that was modified on september 23rd 2017

**Updated from an older installed version or fresh install:** Fresh Install

## Network
**Do you use DHCP?** it is reserved DHCP so it gets the same ip everytime

**Is port 80 and/or 443 open?** yes

]

**Comment by enoch85** [comment]
Hi @coldwolf2000 Thanks for reporting!

The issue you're having is probably due to some configuration error on your end. I admit I haven't tested the SSL generation since Let's Encrypt had downtime on different servers, but there is nothing wrong with the code, that I'm sure of even without testing.

So this is more towards a support question than a bug. Feel free to ask in the nextcloud forums at: https://help.nextcloud.com.

Some advice; open port 443 and 80 in your firewall, and test with an online tool that they are really open.

**Comment by daku97** [comment]
Hello, I can second coldwolf2000's issue as I am seeing the exact same problem. I have tried with both Collabora and Onlyoffice scripts. Differences, I an using a stadic IP address. Error is:

Failed authorization procedure. office.brickcitysolutions.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://office.brickcitysolutions.com/.well-known/acme-challenge/jYtiJ5zEQ_64XMkLWdUWhfk1AviuHo2ehCuf3hPBiV0: Timeout during connect (likely firewall problem)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: office.brickcitysolutions.com
   Type:   connection
   Detail: Fetching
   http://office.brickcitysolutions.com/.well-known/acme-challenge/jYtiJ5zEQ_64XMkLWdUWhfk1AviuHo2ehCuf3hPBiV0:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
It seems like no certs were generated, please report this issue here: https://github.com/nextcloud/vm/issues


coldwolf2000, if you found a workaround, i'd realy like to know what you did?  Thanks

**Comment by enoch85** [comment]
@daku97 As you can see in the description it's likley a firewall issue. "Timeout during connect (likely firewall problem)"

I did a port scan and found that port 80 was closed on your server. Please open port 80 and everything should work.

**Comment by daku97** [comment]
@enoch85 That was it. Sorry!  Thanks again!
