### ISSUE TITLE
Nextcloud VM 13.0.2

### ISSUE THREAD

**Issue by johnczer** [nextcloud/vm#533]
I was going to purchase the latest 13.0.2 for Hyper-V but I downloaded the free one to test it and see if OnlyOffice would work this time since the 13.0.1 build and it appears to install OnlyOffice just fine, according to the script but two things happen after initial install:

- after changing the passwords and resetting the VM it hangs and will not shutdown.  I have to forcibly reboot Hyper-V server
- When I was able to reload the VM OnlyOffice does not run and it's probably due to Docker not appearing to be installed

I am happy to pay the $16 to get the latest Hyper-V VM but I wanted to make sure that this would even install smoothly. I also though one of the changes included PostgreSQL and this was part of the Hyper-V VM for $16 so could you verify that before I purchase?

## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Server version:** (see your admin page)

**VM version** (Scripted install from master **OR** Released version)

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
I installed the Hyper-V version for a customer yesterday and it worked fine. No errors at all. 

I never tested OnlyOffice though. I'd go for Collabora anyway, I think it's better. Since I implemented OnlyOffice in the VM I only had issues reports about it - not Collabora.

I think OnlyOffice has changed something in the proxy config which makes it unreachable, there are an issue about it since before: https://github.com/nextcloud/vm/issues/521
