### ISSUE TITLE
smaller tweaks

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#617]
- [x] Set `clear` in top of all the app scripts + static ip script.
- [x] Fix hyperlink in index.php
- [x] WAN IPv4 doesn't show on a local install (nextcloud.sh)
- [x] Log ModSecurity stuff to seperate log under /apache2
- [x] Remove spamhaus from security.sh or fix it without the Apache mod
- [x] Reformat text in `calculate_max_children`
- [x] Don't restart webserver after php-fpm (to enable it)

**Comment by tiagoefreitas** [comment]
- [alias occ="sudo -u www-data php /var/www/nextcloud/occ"] 
(Useful to disable encryption and other things not available in the UI.)

- [automatically create ncadmin user and give it permissions to nextcloud and all config and logs folders]
(I find myself using root for the autocomplete instead of sudo because of this...)

**Comment by tiagoefreitas** [comment]
$GITHUB_REPO is php-fpm branch instead of master

- [ ] Move $GITHUB_REPO to nextcloud_install_production.sh and pass it to lib.sh

**Comment by enoch85** [comment]
> automatically create ncadmin user and give it permissions to nextcloud and all config and logs folders
(I find myself using root for the autocomplete instead of sudo because of this...)

Will not do that as there are sensitive information in those config files, and the log can e reach from GUI anyway. ncadmin is already the default user in the VM.

I'll implement the rest.

**Comment by enoch85** [comment]
@tiagoefreitas OK, so it's implemented now. Also added `run_nextcloud_update`.
