### ISSUE TITLE
App "ONLYOFFICE" cannot be installed because it is not compatible with this version of the server.

### ISSUE THREAD

**Issue by luisBSBDATA** [nextcloud/vm#641]
## Steps to reproduce
1. Use the "nextcloud_install_production.sh" on an Ubuntu 18.04 server
2. Choose to install Onlyoffice during installation

## Expected behaviour
OnlyOffice should be correctly installed

## Actual behaviour
Tell us what happens instead
![image](https://user-images.githubusercontent.com/37793591/44798815-c1473d80-abb2-11e8-9c2b-ee7506619d85.png)

## Server configuration

**How did you install the VM?** (Scripted install from master **OR** Released version)
I installed an Ubuntu Server 18.04 and used the "nextcloud_install_production.sh" script

## Network
**Do you use DHCP?**
Nope, static IP

**Is port 80 and/or 443 open?**
Yes

**Comment by enoch85** [comment]
Thanks for your report!

I think you should report this to OnlyOffice on Github instead as this is not related to the VM, rather that OnlyOffice can't be run on a specific server version.

**Comment by luisBSBDATA** [comment]
Hi @enoch85, thanks for your reply. I used your onlyoffice.sh script for OnlyOffice installation as well as I used your nextcloud_install_production.sh for Nextcloud installation, aren't you the ones that should make sure that both services versions are compatible between them? If not, I will gladly post on OnlyOffice github.

**Comment by enoch85** [comment]
We download the latest (OnlyOffice/Collabora) Docker available, we also download the latest Nextcloud available. 

What you are saying is that we should stop on let's say Nextcloud 13.0.0 because the OnlyOffice team didn't released code that are compatible with the latest Nextcloud?

The VM offers to install different apps, and make it easier for people to use Nextcloud, if the Apps aren't  maintained we will remove them, but as I'm sure the @onlyoffice team work hard to make it compatible that app will stay in. 

After all, this is just temporary and I'm sure they will fix it soon. Before a release we always test everything properly and it worked when we made the latest release.

 Please report this to OnlyOffice. Thank you!

**Comment by enoch85** [comment]
Sorry @luisBSBDATA I was wrong!

Turned out to be that OnlyOffice changed the repository. It's fixed now and everything is working.

**Comment by enoch85** [comment]
Also, thanks for reporting issues, keep them coming! <3
