### ISSUE TITLE
Module 'redis' already loaded at Unknown#0

### ISSUE THREAD

**Issue by ChuckNozzle** [nextcloud/vm#674]
## Expected behaviour
There shouldn't be so many errors.

## Actual behaviour
I get constant errors that read: Module 'redis' already loaded at Unknown#0

## Server configuration

**Server version:** 14.0.1

**How did you install the VM?** Released version

## Network
**Do you use DHCP?** Yes

**Is port 80 and/or 443 open?** Yes

#### Screenshot
```
![image](https://user-images.githubusercontent.com/29411770/46365793-ce57c080-c679-11e8-9d3f-960bac4977a0.png)
```

#### Log file (/mnt/ncdata/nextcloud.log)
```
[nextcloud.log](https://github.com/nextcloud/vm/files/2439000/nextcloud.log)
```

**Comment by enoch85** [comment]
@ChuckNozzle Which version did you download from start?

The issue here is that Redis is loaded in two places. I suggest you remove one of them by going to `etc/php/7.2/fpm/php.ini` or `etc/php/7.2/fpm/php.ini`(depending on which version you downloaded from start) and put a `#` in from of the redis extension row in the bottom.

This is already fixed in master so nothing to do here.

**Comment by ChuckNozzle** [comment]
It is strange, as I downloaded the VM and set it up about 2 or 3 days ago.

All good, will comment it out...

Thanks

**Comment by enoch85** [comment]
@ChuckNozzle Hmm, I did a fresh installation like 1 week ago and I don't see this issue.

Will test again. Thanks for posting your issue!

**Comment by enoch85** [comment]
Tested again and I don't see such errors.
