### ISSUE TITLE
Implement PageKite

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#680]
https://twitter.com/techandme_se/status/1048077706775203842

@penzoiders @pagekite

**Comment by enoch85** [comment]
cc @pagekite

**Comment by enoch85** [comment]
@penzoiders @pagekite I've started some veeeeeery basic scripting. Feel free to dig in!

**Comment by BjarniRunar** [comment]
Just a quick comment: I really do NOT see PageKite as an "alternative" to Let's Encrypt (that wording was used on the PR).

PageKite is an alternative to punching holes in your firewall or setting up a Tor Hidden Service.

From a security point of view, you absolutely still want Let's Encrypt and end-to-end TLS, even if you're using PageKite. From a performance point of view, just relying on PageKite's wildcard certs (SSL terminated at the relay) may be better, but if you've already got a working Let's Encrypt flow you should absolutely use them together.

**Comment by enoch85** [comment]
@BjarniRunar Thanks for your input. As I'm very novice in PageKite, please help me with the PR. 

It's just a basic PR to get things started, and to get you guys motivated. :) It' easier to edit when things are in place already imo.

To me PageKite is an alternative to using your own domain, which Let's Encrypt will give you, so hence the wording. Could defiantly be improved a lot though.

**Comment by BjarniRunar** [comment]
You can also use your own domain with PageKite. :smile_cat:   I'll be happy to help as soon as I have a bit more time (I am travelling at the moment). I'm leaving this browser tab open...

**Comment by enoch85** [comment]
@BjarniRunar 

> I'm leaving this browser tab open...

Is it still open? :)

**Comment by BjarniRunar** [comment]
Haha, it is now! I'll take a look today and try and send you some advice.

**Comment by BjarniRunar** [comment]
To re-iterate: PageKite is mostly useful for people who don't have a public IP address, and/or don't want to (or cannot for some reason) configure port forwarding in their router. For example if people want to just try spinning up OwnCloud in a VM on their Windows desktop - it's a great fit for that sort of experimenting.

I took a look, but since I haven't tried the Nextcloud setup process, I'm a little bit unsure. But let me have a go... since PageKite is very flexible, it may not make sense to support all the different possible setups at first.

If you assume people go to https://pagekite.net/ first and create an account, then you could get by just asking them for a) the name of their "kite" (e.g. owncloud-user.pagekite.me) and b) the PageKite service shared secret.

With those two bits of information, you can relatively easily generate a PageKite configuration file (I can help with this, for sure!) and expose one or more HTTP or HTTPS services using those details. By structuring the questions and the config generation logic carefully, we could also support alternate (non-pagekite.net) relays and CNAME configurations.

(Slightly fancier, but also more error prone, would be to have the script sign up for a PageKite account automatically. After a fair bit of reflection, I think this might be a bad idea, because it will break in confusing and hard-to-debug ways. It would also mean users might not have visited pagekite.net and might not be aware that it's a for-pay service, causing frustration once the 1-month trial is over.)

Once you have a working pagekite configuration file, you can from there onwards proceed more or less as if the machine had a public IP address and use the DNS names from the pagekite config for the virtual host setup. Even the letsencrypt HTTP auth flow can be made to work.

Is this useful input?

**Comment by enoch85** [comment]
Thanks! Yes it makes sense.

With your help maybe we can go for option 2? Would it be *very* difficult to maintain it?

The whole idea with the VM is to make it as easy as possible to get your own Nextcloud server up and running. That means that everything happens in the first setup, inside the VM. Examples so far (with external services) are Bitwarden, Netdata, Collabora, and OnlyOffice.

I think it would be a good idea to test the VM. Just spin up a VPS according to the recommendations and try it. 

As I think of PageKite now is that it would be an alternative for anyone that doens't know what a port (80|443) is, or don't have a clue about what a webserver does - in other words the most novice users there is. So essentially, just add your PageKite "stuff" and voila, you're up and running. Would that be possible you think?

**Comment by BjarniRunar** [comment]
By "option 2", you mean automate sign-up as well? That is possible, but I'm still of the opinion that it's a bad idea. How about we postpone that decision and get things working with manual signup/credentials first? Once that's stable/useful, we can revisit the fully automated flow?

**Comment by enoch85** [comment]
> By "option 2", you mean automate sign-up as well? That is possible, but I'm still of the opinion that it's a bad idea. How about we postpone that decision and get things working with manual signup/credentials first? Once that's stable/useful, we can revisit the fully automated flow?

Yes.

OK, I agree. Soo, what do you need from me?

**Comment by enoch85** [comment]
@BjarniRunar Leaning towards closing this.

**Comment by enoch85** [comment]
And I'm open to implement option 1 as well btw. Would be best if the user didn't have to leave the console though.

**Comment by BjarniRunar** [comment]
Fair enough, I haven't had time to help out and nobody else has stepped up.

I do feel it's a shame if you're closing this because of a lack of response from *me*. I wasn't the one requesting this feature, I'm not a user of Nextcloud or the VM - but I'm the PageKite guy and I was trying to advise on how to get this done. Obviously I have a financial incentive here, since some users of the feature would probably become customers of mine; but for that very reason I've been a bit shy about barging around hacking on other peoples' projects. It just feels slightly inappropriate. Maybe I'm overthinking that though?

**Comment by enoch85** [comment]
> It just feels slightly inappropriate. Maybe I'm overthinking that though?

Yes you are. :) Open Source (to me) is about (among other things) helping, committing fixes that you benefit from yourself (which is likely in this case) and share it with others, to make the circle complete. Use it, improve it, share your fixes. This repo is a good example; I had issues with installing Nextcloud in the past, so I made it simpler - this repo is the result.

You are the best person to implement this, *and* it should be in your best interest. Hence I'm closing since the lack of response from you. :)

I don't have time, and unfortunately I don't get much help in this repo. I'm (almost) the sole maintainer.

So I guess the ball is in your court on this one. I'm happy to re-open if you feel you have the time and motivation to work on this.

I'm thinking that I will implement some other DDNS service, if you don't change your mind and are willing to start working on this?

**Comment by BjarniRunar** [comment]
I appreciate that you don't feel there's a conflict of interest. That's good to have clarified, thanks.

> I'm thinking that I will implement some other DDNS service, if you don't change your mind and are willing to start working on this?

You don't have time to work on this, but you do have time to work on something else? It's none of my business whether you implement other services, why do you even bring this up? Is this a threat?

You should do what is best for your project. I'll return to this when I have time and I'm no longer annoyed by this exchange. Maybe.

**Comment by enoch85** [comment]
> You don't have time to work on this, but you do have time to work on something else? It's none of my business whether you implement other services, why do you even bring this up? Is this a threat?

I don't have time to work on the other stuff either as of right now, but it's on my TODO-list - which can be tomorrow, next month, or in a year. 

I think it's far-fetched to take it as a threat though. That was not my intention. Sorry if you feel that way. I only mentioned it just because I assumed you saw my newly created issue, and was referring to that. Maybe I'm not that good with words... 

All and all, I just want a service that makes it easier for the VM users to get on with a domain secured by SSL. If that's PageKite or something else doesn't make any difference to me, as long as it works as intended. :rocket: 

Right now there is the default Let's Encrypt scripts, which is quite easy if you ask me. But still, it requires some preparations by the user, and if you don't have a clue about servers, well, then it's kind of hard. Hence a service like we are discussing.

**Comment by enoch85** [comment]
Also, I just want to say that I see this as a win-win. You get PageKite implemented in something that gets downloaded about 100 times per day - this repo would get a service that makes it easier for it's users.
