### ISSUE TITLE
select type of database

### ISSUE THREAD

**Issue by vasyakrg** [nextcloud/vm#710]
it would be great to add a choice of database type
1) postgres
2) mysql-server
3) mariadb-server

**Comment by enoch85** [comment]
The first VM ran MySQL, then we changed to MariaDB and had a lot of issues, so we decided to [change to PostgreSQL](https://www.techandme.se/we-migrated-to-postgresql/), and since then everything has worked very well. It's very fast and avoids errors that MariaDB and MySQL have.

We will not change or give that as an option. PostgreSQL is the best DB in our opinion, and if you want to convert it yourself, you are [free to do so](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/occ_command.html#database-conversion).

**Comment by thejohnha** [comment]
@enoch85 quick question for you: I have an instance that is running mariadb - it was set up with a earlier version of the vm scripts. Do you think there is a way I can migrate my instance to the new version with PostgreSQL? Ideally I'd like to start from scratch and create a brand new instance and then migrate everything over. I've done this before, but it was always from mariadb to mariadb, and not from mariadb to PostgreSQL...

**Comment by vasyakrg** [comment]
> @enoch85 quick question for you: I have an instance that is running mariadb - it was set up with a earlier version of the vm scripts. Do you think there is a way I can migrate my instance to the new version with PostgreSQL? Ideally I'd like to start from scratch and create a brand new instance and then migrate everything over. I've done this before, but it was always from mariadb to mariadb, and not from mariadb to PostgreSQL...

I would not advise moving from an existing base between MariaDB and PostgresSQL

**Comment by enoch85** [comment]
> I would not advise moving from an existing base between MariaDB and PostgresSQL

Why?

It's as simple as creating a new DB, and let the Nextcloud `occ` command do it's job. Read more here: https://www.techandme.se/we-migrated-to-postgresql/ It's been working without a hitch since I deployed it.

**Comment by thejohnha** [comment]
> It's as simple as creating a new DB, and let the Nextcloud `occ` command do it's job. Read more here: https://www.techandme.se/we-migrated-to-postgresql/ It's been working without a hitch since I deployed it.

Sweet - thanks for that! I forgot about that blog post - I'll give it a shot  :-)

**Comment by enoch85** [comment]
@thejohnha Remember, backups backups backups. :)

**Comment by thejohnha** [comment]
> @thejohnha Remember, backups backups backups. :)

:+1::+1::+1::smiley:
