### ISSUE TITLE
Ephemeral update scripts in appliance make debugging harder

### ISSUE THREAD

**Issue by hatclub** [nextcloud/vm#726]
I'd already noticed that you rely on directly sourcing a github hosted lib.sh in the update script rather than pulling and sourcing, but a recent change to your updater appears to have pushed even nextcloud_update into a similar ephemeral state where it is downloaded, executed, and deleted immediately.

This makes debugging any odd behaviour a lot harder than it needs to be - I can see replacing scripts with the newest version upon execution, but what is the purpose of deleting them immediately after execution?

In a similar vein, given curl against raw.github on master is used, rather than anything that might understand/log the git revision history, how does a user find out after the fact exactly which revision of the update scripts/library/etc was downloaded and executed when they have problems, when the master file on github might have changed since the problem was caused?

**Comment by enoch85** [comment]
> recent change to your updater appears to have pushed even nextcloud_update into a similar ephemeral state where it is downloaded, executed, and deleted immediately.

Well, that was a while ago. The reason for it is that `nextcloud_update.sh` shouldn't be used and is easily confused with `update.sh` which is the correct script to use.

If a novice Linux user (read noob) somehow manages to get into the CLI and sees the two files, which do you think he will run? Most likely `nextcloud_update.sh` as it has "nextcloud" in it. We don't want that as the update script doesn't only update Nextcloud, it fixes stuff in the VM as well. The latest example is removing `Headers` and holding the `docker-ce` package since it breaks OnlyOffice and Collabora.

If you on the other hand are a more versed Linux user, you should know that all the scripts are existing in this repo, and probably you can read bash as well. So if you want debugging then download the script manually from this repo and run it.

The update.sh script always fetches the latest `nextcloud_update.sh` so it's quite easy to figure out, just go to this repo and look at the latest script. Because probably, if you get errors is in with the latest script run. 

Makes sense?

**Comment by enoch85** [comment]
Good points!

Since this is open source, you are welcome with a PR to provide what you were asking for.

**Comment by enoch85** [comment]
The command that runs `nextcloud_update.sh` is found [here](https://github.com/nextcloud/vm/blob/master/lib.sh#L614-L636).

**Comment by enoch85** [comment]
@hatclub It just hit me...

Why not just redirect the output when running `run_main_script()` to a log file in `/var/log` and at the same time write the output on screen? If you want several logs, then just add `$(date)` in the log file name. That way it would be very easy to track errors if you run it in a `crontab`.

What do you think?

**Comment by enoch85** [comment]
@hatclub Any progress on this?

**Comment by enoch85** [comment]
This is now implemented in the automated update option.
