### ISSUE TITLE
FTS use ALOT of RAM

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#755]
@Ark74 

When running the FTS docker it consumes very much RAM. Is there any way to limit that? The VM is released with 2 GB RAM per default and that's not sufficient if you choose to run FTS.

I raised my own VM from 6 GB to 12 GB just to run FTS smoothly. That shouldn't be the case.

![screenshot from 2019-01-05 18 35 18](https://user-images.githubusercontent.com/4511254/50727286-12df7600-1119-11e9-94ee-ba2fe374aba3.png)

**Comment by Ark74** [comment]
That's weird.
I run FTS for 2 instances with 4 GB RAM VPS with no issues.

Is this the first index?

> Is there any way to limit that?

My guess is no without hitting performance of operation.

Indexing takes a lot of time, and it will consume as much resources as it can find in order to reduce index time. If you have 4 GB it will take longer than if you have 12 GB, but I will not crash by it self.

2GB is to little if you run more than 1 docker image/app.

I'll re-check but IIRC on the initial setup we followed the ES recommendations to avoid failure.

**Comment by enoch85** [comment]
On Ubuntu 18.04 the swap file is only 980 MB, so that gets filled instantly when a new set of files are added. It doesn't crash, but still - it would be nice if you could tweak it.

**Comment by Ark74** [comment]
Here the PR #756 
As I said earlier ES come already with a lock to 1G, my guess is that fulltextsearch creates several threads what increase significantly the memory usage. Either way locking to ram should help.

Please test.

**Comment by Ark74** [comment]
Closed by ff28069c6ec228e16320e882089689d83303c162
Please reopen if required.

**Comment by enoch85** [comment]
@Ark74 If you add "Fixes #756" in the PR then GitHub will close it automatically once merged. Just an advice. :)
