### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by bobdig** [nextcloud/vm#767]
## Steps to reproduce
1.Installed nexcloud VM
2. This time got an IP
3.

## Expected behaviour
Should connect with browser from WAN and LAN

## Actual behaviour
I always get a 503 Service Unavailable http or https with LAN or WAN address 

## Server configuration
just changed the keyboard layout, everything defaults, no extras, not even fail2ban

I don't know what is going on, had installed the nextcloud VM before months without any problem but today nothing wants to work for me...

**Comment by enoch85** [comment]
Since this more of a support question than a bug, I refer you to the support forum instead.

The only thing I can do with the information you provided is test it myself, and I did - 3 times today without any issues at all. So I guess it's temporary, or something in your setup.

Feel free to re-open if you think it's a bug in the scripts.

**Comment by enoch85** [comment]
OK, so the soulution is to add pm.max_children.

1. `sudo nano /etc/php/7.2/fpm/pool.d/nextcloud.conf`
2. Add `8` after pm.max_children
3. Ctrl+X
4. `sudo service restart php7.2-fpm`

**Comment by enoch85** [comment]
This is now fixed with https://github.com/nextcloud/vm/commit/81004924e3a3bdc1d2bf746d29055c99d8072634
