### ISSUE TITLE
Action is required to prevent your Let's Encrypt certificate renewals from breaking

### ISSUE THREAD

**Issue by Rick26L** [nextcloud/vm#779]
Steps to reproduce
Have a Let's Encrypt Certificate for your Nextcloud which were created and updated by Certbot with ACME TLS-SNI-01.
Receive the Mail from Let's Encrypt "TLS-SNI-01 validation is reaching end-of-life and will stop working on February 13th, 2019."
Question:
What do I have to do to change the validating process to HTTP-01, DNS-01 or TLS-ALPN-01.

Server configuration
Operating system: Ubuntu 16.04

**Web server:**Apache/2.4.37

**Database:**mysql 10.2.19

**PHP version:**7.0.32-0ubuntu0.16.04.1

Nextcloud version: 14.0.4

Where did you install Nextcloud from: Tech and Me

**Comment by enoch85** [comment]
Hi @Rick26L!

It's easy to check if you are running the "correct" version or not. If you are on Acme API V2, then you're fine! You can find the information in `/etc/letsencrypt/renewal/yourdomain.xyz`

It was a long time ago since the scripts used pure TLS validation, so I think you're fine, but better safe than sorry. :)

You have several options:

1. Ask in the Nextcloud forums at https://help.nextcloud.com
2. Check out the Lets Encrypt forums: https://community.letsencrypt.org/
3. [Google](https://www.google.com/search?client=ubuntu&hs=NAb&channel=fs&q=TLS-SNI-01+validation+is+reaching+end-of-life+and+will+stop+working+on+February+13th,+2019+certbot.&spell=1&sa=X&ved=0ahUKEwi2w-nYz5PgAhVKEVAKHRKtCaEQBQgrKAA&biw=1920&bih=913) it.
4. Buy [support](https://shop.hanssonit.se/product/premium-support-per-30-minutes/) in the shop, sit back and relax while someone else fix it.
