### ISSUE TITLE
Broke nextcloud after update

### ISSUE THREAD

**Issue by aneyeforsecrets** [nextcloud/vm#781]
## Steps to reproduce
1. Run do-release-upgrade
2. Reboot
3. Face the consequences

## Expected behaviour
I was running a fairly old installation that I wanted to do some spring-cleaning with. It's been a while I touched it, so I forgot about the extra scripts and junk. Figured do-release-upgrade would work well enough.

## Actual behaviour
It's not working, mildly put.

## Server configuration

**Nextcloud server version:** 
15.02

**Server OS** (Ubuntu server is default)
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**How did you install the VM?** (Scripted install from master **OR** Released version)
Used the VM way back when

## Network
**Do you use DHCP?** - no, static

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots
https://0bin.net/paste/pRwdgwhRzBAGx1C6#fKjmKlMmo1jtQFRwISLFEV4kMXykSFHsa8iBX94TQ1C

#### Log file (/mnt/ncdata/nextcloud.log)
Not sure where it is on that VM, it's not there.

#### Installation log (command output)
Don't have any

**Comment by enoch85** [comment]
Sorry that your VM broke!

 Updating the OS has nothing to do with the scripts or what we develop here in this repo. Neither it's documented due to above reason. You should not upgrade the OS if you're not knowing exactly what needs to be done as it's a quite complex procedure due to all the dependencies that are affected and so on.

**Always use the built in update script (sudo bash var/scripts/update.sh) and don't use anything else**.

If you made a snapshot of the VM:
1. Revert to the snapshot before the upgrade and ask in the forums for help.
OR 2. Revert to the snapshot before the upgrade and buy support in the shop.

If you didn't make a snapshot:
1. Rescue the data and the database
2. Download the latest VM and import the data and the DB
    a) if the DB is different from the old one you need to either migrate the old DB or skip the DB import to the new VM.

Hope it helps!
