### ISSUE TITLE
changing hostname breaks the installation

### ISSUE THREAD

**Issue by wearethesampiyon** [nextcloud/vm#841]
## Steps to reproduce
Using VMware pre-installed 40G ova file: Nextcloud_VM_www.hanssonit.se.ova created 28.05.2019 to deploy and install NextCloud.

Upon import and startup of VM, the guided installation has been avoided in order to set static IP, NM, GW, NS and to change the hostname. Following a reboot, the guided installation was started and completed. Upon completion and following automatic reboot, it was found that the hostname had been changed back to nextcloud. Proceeded to add a trusted domain and that is when I noticed that only localhost was in the list (/var/www/nextcloud/config/config.php). Added the server IP and the fqdn of the server. Rebooted then attempted to launch the web console, secure and non-secure for the fqdn. The Nextcloud UI was not accessible (500) by fqdn.

## Expected behaviour
I was expecting the Nextcloud web console to load.
config.php only had 'localhost', as trusted domain and not the server IP address.

## Actual behaviour
An HTTP 500 error was thrown.

## Server configuration
Default VM parms.

**Nextcloud server version:** (see your admin page)
Admin page non functional.

**Server OS** (Ubuntu server is default)
18.04.2

**How did you install the VM?** (Scripted install from master **OR** Released version)
T&M Hansson VM Appliance

## Network
NO

**Is port 80 and/or 443 open?**
YES

## Logs / Screenshots
N/A

#### Log file (/mnt/ncdata/nextcloud.log)
log is empty

#### Installation log (command output)
wizard based, no output logged on screen.

#### Screenshoots
N/A

**Comment by enoch85** [comment]
Most of the values are hard coded during the first setup, that's why it will change back to 'nextcloud' for hostname for example. You need to run the first setup script the first thing you do, after that is run you can make your own changes. If you don't have DHCP and you need to set a static IP, you will be asked to do so in the beginning of the script.

Please read the docs here: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm

**Comment by wearethesampiyon** [comment]
Hi there,

Thanks for the reply. Can the hard coded values be modified before the installation script gets executed?
If so, could you please inform where are they hard coded?

The automated install script makes deployment super easy, but if the hostname can't be easily modified then the purpose of the script is negated. Having to manually modify all configuration parameters that point to a hostname following the installation, will take as much time as it does to install nextcloud manually.

Please consider including var for defining hostname at pre-install phase.

Can the hard coded values be modified before the installation script gets executed?
If so, could you please inform where are they hard coded?

**Comment by enoch85** [comment]
Why would you like to change the hostname in the first place?

The script is developed to work 'as is' and even if it takes alot of stuff in consideration, it will never cover all possible scenarios. I say never, because that would be as many scenarios as users of the VM/scripts and that's not feasible. 

The default hostname is 'nextcloud' and the only time that changes is when you run the SSL script. The it changes to 'your.cloud.example'.

Changing the hostname shouldn't have any affect on reaching the VM if your network setup is 'normal'. 

As I said, run the initial setup script, and then change the hostname in `/etc/hosts`. As long as you have internet connection the script will run successfully, and I never heard that a hostname fixes that, rather an IP address.

You are also welcome with a PR to fix your issue.

Thanks.
