### ISSUE TITLE
After apt update, no Network

### ISSUE THREAD

**Issue by kanet0x** [nextcloud/vm#850]
I used apt update yesterday, since this. No network anymore.

**Comment by enoch85** [comment]
Always use `sudo bash /var/scripts/update.sh` when updating. 

Please also only report bugs in this repository, if you need help after doing your own custom changes, please use the forum: https://help.nextcloud.com, or https://www.hanssonit.se/#contact for paid support.

**Comment by enoch85** [comment]
For the sake of this *very informative* report, what you say is that:
a) You ran ´apt update && apt upgrade` and the network stopped working?
b) Before you did you used the static IP script to set static IP?
c) You set static IP yourself?
d) You change any network configuration by yourself?

It's highly unlikely that network just stops working when running `apt update && apt upgrade` since:
a) `apt` doesn't touch the network configuration files (.yml)
b)  `apt` doesn't touch any other network settings set by the user

So, provide more information please.

**Comment by enoch85** [comment]
@kanet0x Told me to "Fuck off" via email. Closing this.
