### ISSUE TITLE
"vm/nextcloud_install_production.sh" will delete all *.sh files in my home directory!!!

### ISSUE THREAD

**Issue by dfshan** [nextcloud/vm#880]
This script contains the following aggressive command:
``` bash
find /root "/home/$UNIXUSER" -type f \( -name '*.sh*' -o -name '*.html*' -o -name '*.tar*' -o -name '*.zip*' \) -delete
```
This command will delete all *.sh files in my home directory.

I do not know why you guys write so aggressive command and YOU DONOT HIGHLIGHT IT IN THE DOCUMENTATION!!!

After running this script, lots of useful bash scripts are deleted in my server.
I have to waste a lot of time to rewrite them.

**Comment by enoch85** [comment]
@dfshan Very sorry about that!

The reason is that the scripts are meant to be run in a clean environment, hence all the checks in the beginning. We delete all the files in there as a cleanup procedure. We don't want dangling files all over the place which shouldn't be run after the setup is done.

Will add it to the initial prompt.
