### ISSUE TITLE
Check sum error when loading OVA file

### ISSUE THREAD

**Issue by Klemens2** [nextcloud/vm#922]
## Steps to reproduce
1. Downloading OVA-File (tried 2 times today)
2. Importing in Virtualization Station (Qnap) (tried several times, every time exactly the same error)

## Expected behaviour
VS should load OVA file.

## Actual behaviour
VS interrupts at 25 %. Error message "Failed to import VM: Check-sum error: [SHA256(Nextcloud_VM_www.hanssonit.se.ovf)= 0effdd80ec0b38b21ac9baa28768dea2e93ee7ec70141826a6d76facfecbc649]."

**Comment by enoch85** [comment]
Hi 

Thanks for your report.

Please check old issues before opening new ones. There was an issue like this yesterday: https://github.com/nextcloud/vm/issues/921

Try it in VMware Player. Does it work? Yes? Then that tells me that there is something wrong on the QNAP end. 

There is many users reporting this lately, I have successfully imported the VM on QNAP before. You may need to extract the OVA file in VMware, and then import the OVA since QNAP doesn't support the OVA file it seems.
