### ISSUE TITLE
Setup Script Error in Pre-Configured VM

### ISSUE THREAD

**Issue by SageSam** [nextcloud/vm#953]
Just purchased the 1TB pre-configured NextCloud VM.

Immediately have two major issues right away.

First, localization and keyboard layouts should be one of the first prompts. Extremely, difficult to fill in the prompts for the IP configuration when typing the symbols on my keyboard enter a completely different symbol.

Second, I'm getting the error trying to enter the gateway IP (nextcloud-startup-script.sh: line 177: ask_yes_or_no: command not found).

I see this issue was previously reported and marked as resolved 10 days ago. Are the preconfigured VMs not updated yet? How do I get past this error?

**Comment by enoch85** [comment]
Hi!

Thanks for posting this issue.

This will be in 17.0.0, so it's already solved but not released yet. Send me an email and I'll extend the 10 day period for downloading the VM so that you can get the latest one once Nextcloud 17.0.0 is released.

Please also let me know if [this](https://cloud.hanssonit.se/s/zjsqkrSpzqJGE9N?path=%2FTESTING) works for you.

**Comment by SageSam** [comment]
I cannot test that VM as we are using Hyper-V.

What email would you like me to use?

**Comment by enoch85** [comment]
You can fill in this form: https://www.hanssonit.se/#contact or use the one on Github.

Thanks!
