### ISSUE TITLE
Modsec_audit.log File rotation/recycling

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#956]
So yea my server ran out of disk space (I gave it 100gb for non-ncdata storage on an ssd) and it was because of modsec_audit.log being so large. Took nearly 90gb out of the 100gb.

Recommend daily log rotation and clean up older logs after a while. Maybe 1-2 weeks?

![https://i.imgur.com/FA66aHZ.png](https://i.imgur.com/FA66aHZ.png)

**Comment by enoch85** [comment]
I'm actually thinking of removing this feature all along, it gives more headache than comfort since many (not you) don't know how to use it, or what it's for and just enables it because it had "security" in it - hence the warning when enabling it.

Maybe there's a way of rotating the log in the config file of ModSecurity? Would be super if you could have a look! :+1:

**Comment by BetaLeaf** [comment]
I actually have no idea what it does. My best guess is that it is like an action log, logging whatever people do on my server.

**Comment by enoch85** [comment]
Not valid anymore since Modsecurity are removed.
