### ISSUE TITLE
previews making disk full

### ISSUE THREAD

**Issue by Powerbless** [nextcloud/vm#965]
i am have the newest image from your website and it works very very nice! Thanks for that.

For Testing i upload an Folder with 5GB of pictures and delete then and upload and delete and so on....now i find out that the preview folder getting bigger and bigger and bigger. How can i easy clean up? is there a way? can you implement this in your vm?

Greetings from Germany :-)

**Comment by enoch85** [comment]
Thanks for the feedback!

Please take a look at this: https://github.com/nextcloud/server/issues/5717

**Comment by Powerbless** [comment]
But i am found that the Preview Filder size decreased after Lots of hours after deleting the File from Trash. Is this right? I thought that the previews will be deleted immediately and not hours later.can you confirm it?

**Comment by enoch85** [comment]
In the VM, files are kept in trashbin for 180 days before they are removed (can be edited in config.php). I'm not 100% sure about previews though.

**Comment by Powerbless** [comment]
no no. i had delete the files from the trash too. what do you mean is after how many days, files in the trash are being automatic deleted. but i delete the pictures manual from the trash too.

**Comment by snoopy72** [comment]
I read all the threads regarding those "magically" full preview folders - because i have the same problem here:

15 GB of previews from photos, deleted weeks ago.

i am not able to run bash command son that server AND it is a custom cloud, so my absolut (and non discussable) highest priority is the safety of the existing customer (users) data. so i am not willing to run some of those commands and "solutions" from others threads like "delete the folder" and hopefully it will be restored with massive cpu load over days ?!

i decreased the preview sizes now, but the folder keeps too big.

is there no official working solution ?!

how can i be, that an app fills the folder with tons of data and then "misses" the management of those folder (the privacy rules and laws completly ignoring) ?

**Comment by enoch85** [comment]
@snoopy72 All the `occ` commands are safe to run. FYI. :)

**Comment by snoopy72** [comment]
> 
> 
> @snoopy72 All the `occ` commands are safe to run. FYI. :)

But without bash on that server (for security and NOT changeable), i cannot run occ commands.

btw: if an app creates files, it should remove those files automatically if not required anymore.
it's not the admins job to be manual cleaning staff (just my two cents)

**Comment by enoch85** [comment]
@snoopy72 Are you using the VM scripts? Probably not since you can't use bash. So how is your question related to the Nextcloud VM?

**Comment by snoopy72** [comment]
therefor i already posted the question in "server": https://github.com/nextcloud/server/issues/22003
... but not answers or reactions there up to now.

very, very frustrating.
