### ISSUE TITLE
Remove welcome screen

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#992]
## Steps to reproduce
1. Install with script

## Expected behaviour
visiting the root url of my site should display the login screen, instead it shows the system installation welcome screen.

**How did you install the VM?** Scripted install from master

The system installation welcome  screen shows messages about using webmin and adminer... You have to visit myurl.com/nextcloud/ to show the login screen. Is this an error, because previous versions of the script did not persist the welcome screen.

Thank you Daniel!  :-)

**Comment by enoch85** [comment]
This is by design and will not be changed. 

1. The welcome screen will be shown as long as you didn't activate SSL, which you should.
2. Adminer or Webmin are only reachable locally, not publicly (if your firewall isn't wide open).
3. Nextcloud is reachable via https://ip-adress or http://ip-address/nextclud
4. It's nice to have some summary of what just happened, and what you now can access. 
5. It gives me the opportunity to inform the users about stuff that is important to know
6. The list goes on...

**Comment by thejohnha** [comment]
But @enoch85  I am using a reverse proxy in front of the VM that terminates SSL there. Have you considered that setup?

**Comment by enoch85** [comment]
> Have you considered that setup?

I use it myself. But the VM is not designed to support all different proxies. 

The VM itself has noting to do with the proxy at all, that's a decision made by the end user to use or not. Or did you expect me to script the proxy installation as well for every proxy out there so that it could be chosen from a menu with one click install? :D
